// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package portmock

//go:generate minimock -i sprezz-identity/internal/domain/port.AdminLogonUseCase -o admin_logon_usecase_mock.go -n AdminLogonUseCaseMock -p portmock

import (
	"context"
	"sprezz-identity/internal/domain/model"
	mm_port "sprezz-identity/internal/domain/port"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
	"github.com/google/uuid"
)

// AdminLogonUseCaseMock implements mm_port.AdminLogonUseCase
type AdminLogonUseCaseMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcCompleteAdminLogon          func(ctx context.Context, localTenantID uuid.UUID, incomingState string, incomingCode string) (tp1 *model.TokenSetResponse, s1 string, err error)
	funcCompleteAdminLogonOrigin    string
	inspectFuncCompleteAdminLogon   func(ctx context.Context, localTenantID uuid.UUID, incomingState string, incomingCode string)
	afterCompleteAdminLogonCounter  uint64
	beforeCompleteAdminLogonCounter uint64
	CompleteAdminLogonMock          mAdminLogonUseCaseMockCompleteAdminLogon

	funcInitiateAdminLogon          func(ctx context.Context, localTenantID uuid.UUID, callbackURI string, targetAdminUI string) (ip1 *mm_port.InitiateFederatedLoginResponse, err error)
	funcInitiateAdminLogonOrigin    string
	inspectFuncInitiateAdminLogon   func(ctx context.Context, localTenantID uuid.UUID, callbackURI string, targetAdminUI string)
	afterInitiateAdminLogonCounter  uint64
	beforeInitiateAdminLogonCounter uint64
	InitiateAdminLogonMock          mAdminLogonUseCaseMockInitiateAdminLogon
}

// NewAdminLogonUseCaseMock returns a mock for mm_port.AdminLogonUseCase
func NewAdminLogonUseCaseMock(t minimock.Tester) *AdminLogonUseCaseMock {
	m := &AdminLogonUseCaseMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.CompleteAdminLogonMock = mAdminLogonUseCaseMockCompleteAdminLogon{mock: m}
	m.CompleteAdminLogonMock.callArgs = []*AdminLogonUseCaseMockCompleteAdminLogonParams{}

	m.InitiateAdminLogonMock = mAdminLogonUseCaseMockInitiateAdminLogon{mock: m}
	m.InitiateAdminLogonMock.callArgs = []*AdminLogonUseCaseMockInitiateAdminLogonParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mAdminLogonUseCaseMockCompleteAdminLogon struct {
	optional           bool
	mock               *AdminLogonUseCaseMock
	defaultExpectation *AdminLogonUseCaseMockCompleteAdminLogonExpectation
	expectations       []*AdminLogonUseCaseMockCompleteAdminLogonExpectation

	callArgs []*AdminLogonUseCaseMockCompleteAdminLogonParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// AdminLogonUseCaseMockCompleteAdminLogonExpectation specifies expectation struct of the AdminLogonUseCase.CompleteAdminLogon
type AdminLogonUseCaseMockCompleteAdminLogonExpectation struct {
	mock               *AdminLogonUseCaseMock
	params             *AdminLogonUseCaseMockCompleteAdminLogonParams
	paramPtrs          *AdminLogonUseCaseMockCompleteAdminLogonParamPtrs
	expectationOrigins AdminLogonUseCaseMockCompleteAdminLogonExpectationOrigins
	results            *AdminLogonUseCaseMockCompleteAdminLogonResults
	returnOrigin       string
	Counter            uint64
}

// AdminLogonUseCaseMockCompleteAdminLogonParams contains parameters of the AdminLogonUseCase.CompleteAdminLogon
type AdminLogonUseCaseMockCompleteAdminLogonParams struct {
	ctx           context.Context
	localTenantID uuid.UUID
	incomingState string
	incomingCode  string
}

// AdminLogonUseCaseMockCompleteAdminLogonParamPtrs contains pointers to parameters of the AdminLogonUseCase.CompleteAdminLogon
type AdminLogonUseCaseMockCompleteAdminLogonParamPtrs struct {
	ctx           *context.Context
	localTenantID *uuid.UUID
	incomingState *string
	incomingCode  *string
}

// AdminLogonUseCaseMockCompleteAdminLogonResults contains results of the AdminLogonUseCase.CompleteAdminLogon
type AdminLogonUseCaseMockCompleteAdminLogonResults struct {
	tp1 *model.TokenSetResponse
	s1  string
	err error
}

// AdminLogonUseCaseMockCompleteAdminLogonOrigins contains origins of expectations of the AdminLogonUseCase.CompleteAdminLogon
type AdminLogonUseCaseMockCompleteAdminLogonExpectationOrigins struct {
	origin              string
	originCtx           string
	originLocalTenantID string
	originIncomingState string
	originIncomingCode  string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmCompleteAdminLogon *mAdminLogonUseCaseMockCompleteAdminLogon) Optional() *mAdminLogonUseCaseMockCompleteAdminLogon {
	mmCompleteAdminLogon.optional = true
	return mmCompleteAdminLogon
}

// Expect sets up expected params for AdminLogonUseCase.CompleteAdminLogon
func (mmCompleteAdminLogon *mAdminLogonUseCaseMockCompleteAdminLogon) Expect(ctx context.Context, localTenantID uuid.UUID, incomingState string, incomingCode string) *mAdminLogonUseCaseMockCompleteAdminLogon {
	if mmCompleteAdminLogon.mock.funcCompleteAdminLogon != nil {
		mmCompleteAdminLogon.mock.t.Fatalf("AdminLogonUseCaseMock.CompleteAdminLogon mock is already set by Set")
	}

	if mmCompleteAdminLogon.defaultExpectation == nil {
		mmCompleteAdminLogon.defaultExpectation = &AdminLogonUseCaseMockCompleteAdminLogonExpectation{}
	}

	if mmCompleteAdminLogon.defaultExpectation.paramPtrs != nil {
		mmCompleteAdminLogon.mock.t.Fatalf("AdminLogonUseCaseMock.CompleteAdminLogon mock is already set by ExpectParams functions")
	}

	mmCompleteAdminLogon.defaultExpectation.params = &AdminLogonUseCaseMockCompleteAdminLogonParams{ctx, localTenantID, incomingState, incomingCode}
	mmCompleteAdminLogon.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmCompleteAdminLogon.expectations {
		if minimock.Equal(e.params, mmCompleteAdminLogon.defaultExpectation.params) {
			mmCompleteAdminLogon.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmCompleteAdminLogon.defaultExpectation.params)
		}
	}

	return mmCompleteAdminLogon
}

// ExpectCtxParam1 sets up expected param ctx for AdminLogonUseCase.CompleteAdminLogon
func (mmCompleteAdminLogon *mAdminLogonUseCaseMockCompleteAdminLogon) ExpectCtxParam1(ctx context.Context) *mAdminLogonUseCaseMockCompleteAdminLogon {
	if mmCompleteAdminLogon.mock.funcCompleteAdminLogon != nil {
		mmCompleteAdminLogon.mock.t.Fatalf("AdminLogonUseCaseMock.CompleteAdminLogon mock is already set by Set")
	}

	if mmCompleteAdminLogon.defaultExpectation == nil {
		mmCompleteAdminLogon.defaultExpectation = &AdminLogonUseCaseMockCompleteAdminLogonExpectation{}
	}

	if mmCompleteAdminLogon.defaultExpectation.params != nil {
		mmCompleteAdminLogon.mock.t.Fatalf("AdminLogonUseCaseMock.CompleteAdminLogon mock is already set by Expect")
	}

	if mmCompleteAdminLogon.defaultExpectation.paramPtrs == nil {
		mmCompleteAdminLogon.defaultExpectation.paramPtrs = &AdminLogonUseCaseMockCompleteAdminLogonParamPtrs{}
	}
	mmCompleteAdminLogon.defaultExpectation.paramPtrs.ctx = &ctx
	mmCompleteAdminLogon.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmCompleteAdminLogon
}

// ExpectLocalTenantIDParam2 sets up expected param localTenantID for AdminLogonUseCase.CompleteAdminLogon
func (mmCompleteAdminLogon *mAdminLogonUseCaseMockCompleteAdminLogon) ExpectLocalTenantIDParam2(localTenantID uuid.UUID) *mAdminLogonUseCaseMockCompleteAdminLogon {
	if mmCompleteAdminLogon.mock.funcCompleteAdminLogon != nil {
		mmCompleteAdminLogon.mock.t.Fatalf("AdminLogonUseCaseMock.CompleteAdminLogon mock is already set by Set")
	}

	if mmCompleteAdminLogon.defaultExpectation == nil {
		mmCompleteAdminLogon.defaultExpectation = &AdminLogonUseCaseMockCompleteAdminLogonExpectation{}
	}

	if mmCompleteAdminLogon.defaultExpectation.params != nil {
		mmCompleteAdminLogon.mock.t.Fatalf("AdminLogonUseCaseMock.CompleteAdminLogon mock is already set by Expect")
	}

	if mmCompleteAdminLogon.defaultExpectation.paramPtrs == nil {
		mmCompleteAdminLogon.defaultExpectation.paramPtrs = &AdminLogonUseCaseMockCompleteAdminLogonParamPtrs{}
	}
	mmCompleteAdminLogon.defaultExpectation.paramPtrs.localTenantID = &localTenantID
	mmCompleteAdminLogon.defaultExpectation.expectationOrigins.originLocalTenantID = minimock.CallerInfo(1)

	return mmCompleteAdminLogon
}

// ExpectIncomingStateParam3 sets up expected param incomingState for AdminLogonUseCase.CompleteAdminLogon
func (mmCompleteAdminLogon *mAdminLogonUseCaseMockCompleteAdminLogon) ExpectIncomingStateParam3(incomingState string) *mAdminLogonUseCaseMockCompleteAdminLogon {
	if mmCompleteAdminLogon.mock.funcCompleteAdminLogon != nil {
		mmCompleteAdminLogon.mock.t.Fatalf("AdminLogonUseCaseMock.CompleteAdminLogon mock is already set by Set")
	}

	if mmCompleteAdminLogon.defaultExpectation == nil {
		mmCompleteAdminLogon.defaultExpectation = &AdminLogonUseCaseMockCompleteAdminLogonExpectation{}
	}

	if mmCompleteAdminLogon.defaultExpectation.params != nil {
		mmCompleteAdminLogon.mock.t.Fatalf("AdminLogonUseCaseMock.CompleteAdminLogon mock is already set by Expect")
	}

	if mmCompleteAdminLogon.defaultExpectation.paramPtrs == nil {
		mmCompleteAdminLogon.defaultExpectation.paramPtrs = &AdminLogonUseCaseMockCompleteAdminLogonParamPtrs{}
	}
	mmCompleteAdminLogon.defaultExpectation.paramPtrs.incomingState = &incomingState
	mmCompleteAdminLogon.defaultExpectation.expectationOrigins.originIncomingState = minimock.CallerInfo(1)

	return mmCompleteAdminLogon
}

// ExpectIncomingCodeParam4 sets up expected param incomingCode for AdminLogonUseCase.CompleteAdminLogon
func (mmCompleteAdminLogon *mAdminLogonUseCaseMockCompleteAdminLogon) ExpectIncomingCodeParam4(incomingCode string) *mAdminLogonUseCaseMockCompleteAdminLogon {
	if mmCompleteAdminLogon.mock.funcCompleteAdminLogon != nil {
		mmCompleteAdminLogon.mock.t.Fatalf("AdminLogonUseCaseMock.CompleteAdminLogon mock is already set by Set")
	}

	if mmCompleteAdminLogon.defaultExpectation == nil {
		mmCompleteAdminLogon.defaultExpectation = &AdminLogonUseCaseMockCompleteAdminLogonExpectation{}
	}

	if mmCompleteAdminLogon.defaultExpectation.params != nil {
		mmCompleteAdminLogon.mock.t.Fatalf("AdminLogonUseCaseMock.CompleteAdminLogon mock is already set by Expect")
	}

	if mmCompleteAdminLogon.defaultExpectation.paramPtrs == nil {
		mmCompleteAdminLogon.defaultExpectation.paramPtrs = &AdminLogonUseCaseMockCompleteAdminLogonParamPtrs{}
	}
	mmCompleteAdminLogon.defaultExpectation.paramPtrs.incomingCode = &incomingCode
	mmCompleteAdminLogon.defaultExpectation.expectationOrigins.originIncomingCode = minimock.CallerInfo(1)

	return mmCompleteAdminLogon
}

// Inspect accepts an inspector function that has same arguments as the AdminLogonUseCase.CompleteAdminLogon
func (mmCompleteAdminLogon *mAdminLogonUseCaseMockCompleteAdminLogon) Inspect(f func(ctx context.Context, localTenantID uuid.UUID, incomingState string, incomingCode string)) *mAdminLogonUseCaseMockCompleteAdminLogon {
	if mmCompleteAdminLogon.mock.inspectFuncCompleteAdminLogon != nil {
		mmCompleteAdminLogon.mock.t.Fatalf("Inspect function is already set for AdminLogonUseCaseMock.CompleteAdminLogon")
	}

	mmCompleteAdminLogon.mock.inspectFuncCompleteAdminLogon = f

	return mmCompleteAdminLogon
}

// Return sets up results that will be returned by AdminLogonUseCase.CompleteAdminLogon
func (mmCompleteAdminLogon *mAdminLogonUseCaseMockCompleteAdminLogon) Return(tp1 *model.TokenSetResponse, s1 string, err error) *AdminLogonUseCaseMock {
	if mmCompleteAdminLogon.mock.funcCompleteAdminLogon != nil {
		mmCompleteAdminLogon.mock.t.Fatalf("AdminLogonUseCaseMock.CompleteAdminLogon mock is already set by Set")
	}

	if mmCompleteAdminLogon.defaultExpectation == nil {
		mmCompleteAdminLogon.defaultExpectation = &AdminLogonUseCaseMockCompleteAdminLogonExpectation{mock: mmCompleteAdminLogon.mock}
	}
	mmCompleteAdminLogon.defaultExpectation.results = &AdminLogonUseCaseMockCompleteAdminLogonResults{tp1, s1, err}
	mmCompleteAdminLogon.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmCompleteAdminLogon.mock
}

// Set uses given function f to mock the AdminLogonUseCase.CompleteAdminLogon method
func (mmCompleteAdminLogon *mAdminLogonUseCaseMockCompleteAdminLogon) Set(f func(ctx context.Context, localTenantID uuid.UUID, incomingState string, incomingCode string) (tp1 *model.TokenSetResponse, s1 string, err error)) *AdminLogonUseCaseMock {
	if mmCompleteAdminLogon.defaultExpectation != nil {
		mmCompleteAdminLogon.mock.t.Fatalf("Default expectation is already set for the AdminLogonUseCase.CompleteAdminLogon method")
	}

	if len(mmCompleteAdminLogon.expectations) > 0 {
		mmCompleteAdminLogon.mock.t.Fatalf("Some expectations are already set for the AdminLogonUseCase.CompleteAdminLogon method")
	}

	mmCompleteAdminLogon.mock.funcCompleteAdminLogon = f
	mmCompleteAdminLogon.mock.funcCompleteAdminLogonOrigin = minimock.CallerInfo(1)
	return mmCompleteAdminLogon.mock
}

// When sets expectation for the AdminLogonUseCase.CompleteAdminLogon which will trigger the result defined by the following
// Then helper
func (mmCompleteAdminLogon *mAdminLogonUseCaseMockCompleteAdminLogon) When(ctx context.Context, localTenantID uuid.UUID, incomingState string, incomingCode string) *AdminLogonUseCaseMockCompleteAdminLogonExpectation {
	if mmCompleteAdminLogon.mock.funcCompleteAdminLogon != nil {
		mmCompleteAdminLogon.mock.t.Fatalf("AdminLogonUseCaseMock.CompleteAdminLogon mock is already set by Set")
	}

	expectation := &AdminLogonUseCaseMockCompleteAdminLogonExpectation{
		mock:               mmCompleteAdminLogon.mock,
		params:             &AdminLogonUseCaseMockCompleteAdminLogonParams{ctx, localTenantID, incomingState, incomingCode},
		expectationOrigins: AdminLogonUseCaseMockCompleteAdminLogonExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmCompleteAdminLogon.expectations = append(mmCompleteAdminLogon.expectations, expectation)
	return expectation
}

// Then sets up AdminLogonUseCase.CompleteAdminLogon return parameters for the expectation previously defined by the When method
func (e *AdminLogonUseCaseMockCompleteAdminLogonExpectation) Then(tp1 *model.TokenSetResponse, s1 string, err error) *AdminLogonUseCaseMock {
	e.results = &AdminLogonUseCaseMockCompleteAdminLogonResults{tp1, s1, err}
	return e.mock
}

// Times sets number of times AdminLogonUseCase.CompleteAdminLogon should be invoked
func (mmCompleteAdminLogon *mAdminLogonUseCaseMockCompleteAdminLogon) Times(n uint64) *mAdminLogonUseCaseMockCompleteAdminLogon {
	if n == 0 {
		mmCompleteAdminLogon.mock.t.Fatalf("Times of AdminLogonUseCaseMock.CompleteAdminLogon mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmCompleteAdminLogon.expectedInvocations, n)
	mmCompleteAdminLogon.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmCompleteAdminLogon
}

func (mmCompleteAdminLogon *mAdminLogonUseCaseMockCompleteAdminLogon) invocationsDone() bool {
	if len(mmCompleteAdminLogon.expectations) == 0 && mmCompleteAdminLogon.defaultExpectation == nil && mmCompleteAdminLogon.mock.funcCompleteAdminLogon == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmCompleteAdminLogon.mock.afterCompleteAdminLogonCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmCompleteAdminLogon.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// CompleteAdminLogon implements mm_port.AdminLogonUseCase
func (mmCompleteAdminLogon *AdminLogonUseCaseMock) CompleteAdminLogon(ctx context.Context, localTenantID uuid.UUID, incomingState string, incomingCode string) (tp1 *model.TokenSetResponse, s1 string, err error) {
	mm_atomic.AddUint64(&mmCompleteAdminLogon.beforeCompleteAdminLogonCounter, 1)
	defer mm_atomic.AddUint64(&mmCompleteAdminLogon.afterCompleteAdminLogonCounter, 1)

	mmCompleteAdminLogon.t.Helper()

	if mmCompleteAdminLogon.inspectFuncCompleteAdminLogon != nil {
		mmCompleteAdminLogon.inspectFuncCompleteAdminLogon(ctx, localTenantID, incomingState, incomingCode)
	}

	mm_params := AdminLogonUseCaseMockCompleteAdminLogonParams{ctx, localTenantID, incomingState, incomingCode}

	// Record call args
	mmCompleteAdminLogon.CompleteAdminLogonMock.mutex.Lock()
	mmCompleteAdminLogon.CompleteAdminLogonMock.callArgs = append(mmCompleteAdminLogon.CompleteAdminLogonMock.callArgs, &mm_params)
	mmCompleteAdminLogon.CompleteAdminLogonMock.mutex.Unlock()

	for _, e := range mmCompleteAdminLogon.CompleteAdminLogonMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.tp1, e.results.s1, e.results.err
		}
	}

	if mmCompleteAdminLogon.CompleteAdminLogonMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmCompleteAdminLogon.CompleteAdminLogonMock.defaultExpectation.Counter, 1)
		mm_want := mmCompleteAdminLogon.CompleteAdminLogonMock.defaultExpectation.params
		mm_want_ptrs := mmCompleteAdminLogon.CompleteAdminLogonMock.defaultExpectation.paramPtrs

		mm_got := AdminLogonUseCaseMockCompleteAdminLogonParams{ctx, localTenantID, incomingState, incomingCode}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmCompleteAdminLogon.t.Errorf("AdminLogonUseCaseMock.CompleteAdminLogon got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCompleteAdminLogon.CompleteAdminLogonMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.localTenantID != nil && !minimock.Equal(*mm_want_ptrs.localTenantID, mm_got.localTenantID) {
				mmCompleteAdminLogon.t.Errorf("AdminLogonUseCaseMock.CompleteAdminLogon got unexpected parameter localTenantID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCompleteAdminLogon.CompleteAdminLogonMock.defaultExpectation.expectationOrigins.originLocalTenantID, *mm_want_ptrs.localTenantID, mm_got.localTenantID, minimock.Diff(*mm_want_ptrs.localTenantID, mm_got.localTenantID))
			}

			if mm_want_ptrs.incomingState != nil && !minimock.Equal(*mm_want_ptrs.incomingState, mm_got.incomingState) {
				mmCompleteAdminLogon.t.Errorf("AdminLogonUseCaseMock.CompleteAdminLogon got unexpected parameter incomingState, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCompleteAdminLogon.CompleteAdminLogonMock.defaultExpectation.expectationOrigins.originIncomingState, *mm_want_ptrs.incomingState, mm_got.incomingState, minimock.Diff(*mm_want_ptrs.incomingState, mm_got.incomingState))
			}

			if mm_want_ptrs.incomingCode != nil && !minimock.Equal(*mm_want_ptrs.incomingCode, mm_got.incomingCode) {
				mmCompleteAdminLogon.t.Errorf("AdminLogonUseCaseMock.CompleteAdminLogon got unexpected parameter incomingCode, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCompleteAdminLogon.CompleteAdminLogonMock.defaultExpectation.expectationOrigins.originIncomingCode, *mm_want_ptrs.incomingCode, mm_got.incomingCode, minimock.Diff(*mm_want_ptrs.incomingCode, mm_got.incomingCode))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmCompleteAdminLogon.t.Errorf("AdminLogonUseCaseMock.CompleteAdminLogon got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmCompleteAdminLogon.CompleteAdminLogonMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmCompleteAdminLogon.CompleteAdminLogonMock.defaultExpectation.results
		if mm_results == nil {
			mmCompleteAdminLogon.t.Fatal("No results are set for the AdminLogonUseCaseMock.CompleteAdminLogon")
		}
		return (*mm_results).tp1, (*mm_results).s1, (*mm_results).err
	}
	if mmCompleteAdminLogon.funcCompleteAdminLogon != nil {
		return mmCompleteAdminLogon.funcCompleteAdminLogon(ctx, localTenantID, incomingState, incomingCode)
	}
	mmCompleteAdminLogon.t.Fatalf("Unexpected call to AdminLogonUseCaseMock.CompleteAdminLogon. %v %v %v %v", ctx, localTenantID, incomingState, incomingCode)
	return
}

// CompleteAdminLogonAfterCounter returns a count of finished AdminLogonUseCaseMock.CompleteAdminLogon invocations
func (mmCompleteAdminLogon *AdminLogonUseCaseMock) CompleteAdminLogonAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCompleteAdminLogon.afterCompleteAdminLogonCounter)
}

// CompleteAdminLogonBeforeCounter returns a count of AdminLogonUseCaseMock.CompleteAdminLogon invocations
func (mmCompleteAdminLogon *AdminLogonUseCaseMock) CompleteAdminLogonBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCompleteAdminLogon.beforeCompleteAdminLogonCounter)
}

// Calls returns a list of arguments used in each call to AdminLogonUseCaseMock.CompleteAdminLogon.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmCompleteAdminLogon *mAdminLogonUseCaseMockCompleteAdminLogon) Calls() []*AdminLogonUseCaseMockCompleteAdminLogonParams {
	mmCompleteAdminLogon.mutex.RLock()

	argCopy := make([]*AdminLogonUseCaseMockCompleteAdminLogonParams, len(mmCompleteAdminLogon.callArgs))
	copy(argCopy, mmCompleteAdminLogon.callArgs)

	mmCompleteAdminLogon.mutex.RUnlock()

	return argCopy
}

// MinimockCompleteAdminLogonDone returns true if the count of the CompleteAdminLogon invocations corresponds
// the number of defined expectations
func (m *AdminLogonUseCaseMock) MinimockCompleteAdminLogonDone() bool {
	if m.CompleteAdminLogonMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.CompleteAdminLogonMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.CompleteAdminLogonMock.invocationsDone()
}

// MinimockCompleteAdminLogonInspect logs each unmet expectation
func (m *AdminLogonUseCaseMock) MinimockCompleteAdminLogonInspect() {
	for _, e := range m.CompleteAdminLogonMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to AdminLogonUseCaseMock.CompleteAdminLogon at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterCompleteAdminLogonCounter := mm_atomic.LoadUint64(&m.afterCompleteAdminLogonCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.CompleteAdminLogonMock.defaultExpectation != nil && afterCompleteAdminLogonCounter < 1 {
		if m.CompleteAdminLogonMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to AdminLogonUseCaseMock.CompleteAdminLogon at\n%s", m.CompleteAdminLogonMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to AdminLogonUseCaseMock.CompleteAdminLogon at\n%s with params: %#v", m.CompleteAdminLogonMock.defaultExpectation.expectationOrigins.origin, *m.CompleteAdminLogonMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcCompleteAdminLogon != nil && afterCompleteAdminLogonCounter < 1 {
		m.t.Errorf("Expected call to AdminLogonUseCaseMock.CompleteAdminLogon at\n%s", m.funcCompleteAdminLogonOrigin)
	}

	if !m.CompleteAdminLogonMock.invocationsDone() && afterCompleteAdminLogonCounter > 0 {
		m.t.Errorf("Expected %d calls to AdminLogonUseCaseMock.CompleteAdminLogon at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.CompleteAdminLogonMock.expectedInvocations), m.CompleteAdminLogonMock.expectedInvocationsOrigin, afterCompleteAdminLogonCounter)
	}
}

type mAdminLogonUseCaseMockInitiateAdminLogon struct {
	optional           bool
	mock               *AdminLogonUseCaseMock
	defaultExpectation *AdminLogonUseCaseMockInitiateAdminLogonExpectation
	expectations       []*AdminLogonUseCaseMockInitiateAdminLogonExpectation

	callArgs []*AdminLogonUseCaseMockInitiateAdminLogonParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// AdminLogonUseCaseMockInitiateAdminLogonExpectation specifies expectation struct of the AdminLogonUseCase.InitiateAdminLogon
type AdminLogonUseCaseMockInitiateAdminLogonExpectation struct {
	mock               *AdminLogonUseCaseMock
	params             *AdminLogonUseCaseMockInitiateAdminLogonParams
	paramPtrs          *AdminLogonUseCaseMockInitiateAdminLogonParamPtrs
	expectationOrigins AdminLogonUseCaseMockInitiateAdminLogonExpectationOrigins
	results            *AdminLogonUseCaseMockInitiateAdminLogonResults
	returnOrigin       string
	Counter            uint64
}

// AdminLogonUseCaseMockInitiateAdminLogonParams contains parameters of the AdminLogonUseCase.InitiateAdminLogon
type AdminLogonUseCaseMockInitiateAdminLogonParams struct {
	ctx           context.Context
	localTenantID uuid.UUID
	callbackURI   string
	targetAdminUI string
}

// AdminLogonUseCaseMockInitiateAdminLogonParamPtrs contains pointers to parameters of the AdminLogonUseCase.InitiateAdminLogon
type AdminLogonUseCaseMockInitiateAdminLogonParamPtrs struct {
	ctx           *context.Context
	localTenantID *uuid.UUID
	callbackURI   *string
	targetAdminUI *string
}

// AdminLogonUseCaseMockInitiateAdminLogonResults contains results of the AdminLogonUseCase.InitiateAdminLogon
type AdminLogonUseCaseMockInitiateAdminLogonResults struct {
	ip1 *mm_port.InitiateFederatedLoginResponse
	err error
}

// AdminLogonUseCaseMockInitiateAdminLogonOrigins contains origins of expectations of the AdminLogonUseCase.InitiateAdminLogon
type AdminLogonUseCaseMockInitiateAdminLogonExpectationOrigins struct {
	origin              string
	originCtx           string
	originLocalTenantID string
	originCallbackURI   string
	originTargetAdminUI string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmInitiateAdminLogon *mAdminLogonUseCaseMockInitiateAdminLogon) Optional() *mAdminLogonUseCaseMockInitiateAdminLogon {
	mmInitiateAdminLogon.optional = true
	return mmInitiateAdminLogon
}

// Expect sets up expected params for AdminLogonUseCase.InitiateAdminLogon
func (mmInitiateAdminLogon *mAdminLogonUseCaseMockInitiateAdminLogon) Expect(ctx context.Context, localTenantID uuid.UUID, callbackURI string, targetAdminUI string) *mAdminLogonUseCaseMockInitiateAdminLogon {
	if mmInitiateAdminLogon.mock.funcInitiateAdminLogon != nil {
		mmInitiateAdminLogon.mock.t.Fatalf("AdminLogonUseCaseMock.InitiateAdminLogon mock is already set by Set")
	}

	if mmInitiateAdminLogon.defaultExpectation == nil {
		mmInitiateAdminLogon.defaultExpectation = &AdminLogonUseCaseMockInitiateAdminLogonExpectation{}
	}

	if mmInitiateAdminLogon.defaultExpectation.paramPtrs != nil {
		mmInitiateAdminLogon.mock.t.Fatalf("AdminLogonUseCaseMock.InitiateAdminLogon mock is already set by ExpectParams functions")
	}

	mmInitiateAdminLogon.defaultExpectation.params = &AdminLogonUseCaseMockInitiateAdminLogonParams{ctx, localTenantID, callbackURI, targetAdminUI}
	mmInitiateAdminLogon.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmInitiateAdminLogon.expectations {
		if minimock.Equal(e.params, mmInitiateAdminLogon.defaultExpectation.params) {
			mmInitiateAdminLogon.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmInitiateAdminLogon.defaultExpectation.params)
		}
	}

	return mmInitiateAdminLogon
}

// ExpectCtxParam1 sets up expected param ctx for AdminLogonUseCase.InitiateAdminLogon
func (mmInitiateAdminLogon *mAdminLogonUseCaseMockInitiateAdminLogon) ExpectCtxParam1(ctx context.Context) *mAdminLogonUseCaseMockInitiateAdminLogon {
	if mmInitiateAdminLogon.mock.funcInitiateAdminLogon != nil {
		mmInitiateAdminLogon.mock.t.Fatalf("AdminLogonUseCaseMock.InitiateAdminLogon mock is already set by Set")
	}

	if mmInitiateAdminLogon.defaultExpectation == nil {
		mmInitiateAdminLogon.defaultExpectation = &AdminLogonUseCaseMockInitiateAdminLogonExpectation{}
	}

	if mmInitiateAdminLogon.defaultExpectation.params != nil {
		mmInitiateAdminLogon.mock.t.Fatalf("AdminLogonUseCaseMock.InitiateAdminLogon mock is already set by Expect")
	}

	if mmInitiateAdminLogon.defaultExpectation.paramPtrs == nil {
		mmInitiateAdminLogon.defaultExpectation.paramPtrs = &AdminLogonUseCaseMockInitiateAdminLogonParamPtrs{}
	}
	mmInitiateAdminLogon.defaultExpectation.paramPtrs.ctx = &ctx
	mmInitiateAdminLogon.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmInitiateAdminLogon
}

// ExpectLocalTenantIDParam2 sets up expected param localTenantID for AdminLogonUseCase.InitiateAdminLogon
func (mmInitiateAdminLogon *mAdminLogonUseCaseMockInitiateAdminLogon) ExpectLocalTenantIDParam2(localTenantID uuid.UUID) *mAdminLogonUseCaseMockInitiateAdminLogon {
	if mmInitiateAdminLogon.mock.funcInitiateAdminLogon != nil {
		mmInitiateAdminLogon.mock.t.Fatalf("AdminLogonUseCaseMock.InitiateAdminLogon mock is already set by Set")
	}

	if mmInitiateAdminLogon.defaultExpectation == nil {
		mmInitiateAdminLogon.defaultExpectation = &AdminLogonUseCaseMockInitiateAdminLogonExpectation{}
	}

	if mmInitiateAdminLogon.defaultExpectation.params != nil {
		mmInitiateAdminLogon.mock.t.Fatalf("AdminLogonUseCaseMock.InitiateAdminLogon mock is already set by Expect")
	}

	if mmInitiateAdminLogon.defaultExpectation.paramPtrs == nil {
		mmInitiateAdminLogon.defaultExpectation.paramPtrs = &AdminLogonUseCaseMockInitiateAdminLogonParamPtrs{}
	}
	mmInitiateAdminLogon.defaultExpectation.paramPtrs.localTenantID = &localTenantID
	mmInitiateAdminLogon.defaultExpectation.expectationOrigins.originLocalTenantID = minimock.CallerInfo(1)

	return mmInitiateAdminLogon
}

// ExpectCallbackURIParam3 sets up expected param callbackURI for AdminLogonUseCase.InitiateAdminLogon
func (mmInitiateAdminLogon *mAdminLogonUseCaseMockInitiateAdminLogon) ExpectCallbackURIParam3(callbackURI string) *mAdminLogonUseCaseMockInitiateAdminLogon {
	if mmInitiateAdminLogon.mock.funcInitiateAdminLogon != nil {
		mmInitiateAdminLogon.mock.t.Fatalf("AdminLogonUseCaseMock.InitiateAdminLogon mock is already set by Set")
	}

	if mmInitiateAdminLogon.defaultExpectation == nil {
		mmInitiateAdminLogon.defaultExpectation = &AdminLogonUseCaseMockInitiateAdminLogonExpectation{}
	}

	if mmInitiateAdminLogon.defaultExpectation.params != nil {
		mmInitiateAdminLogon.mock.t.Fatalf("AdminLogonUseCaseMock.InitiateAdminLogon mock is already set by Expect")
	}

	if mmInitiateAdminLogon.defaultExpectation.paramPtrs == nil {
		mmInitiateAdminLogon.defaultExpectation.paramPtrs = &AdminLogonUseCaseMockInitiateAdminLogonParamPtrs{}
	}
	mmInitiateAdminLogon.defaultExpectation.paramPtrs.callbackURI = &callbackURI
	mmInitiateAdminLogon.defaultExpectation.expectationOrigins.originCallbackURI = minimock.CallerInfo(1)

	return mmInitiateAdminLogon
}

// ExpectTargetAdminUIParam4 sets up expected param targetAdminUI for AdminLogonUseCase.InitiateAdminLogon
func (mmInitiateAdminLogon *mAdminLogonUseCaseMockInitiateAdminLogon) ExpectTargetAdminUIParam4(targetAdminUI string) *mAdminLogonUseCaseMockInitiateAdminLogon {
	if mmInitiateAdminLogon.mock.funcInitiateAdminLogon != nil {
		mmInitiateAdminLogon.mock.t.Fatalf("AdminLogonUseCaseMock.InitiateAdminLogon mock is already set by Set")
	}

	if mmInitiateAdminLogon.defaultExpectation == nil {
		mmInitiateAdminLogon.defaultExpectation = &AdminLogonUseCaseMockInitiateAdminLogonExpectation{}
	}

	if mmInitiateAdminLogon.defaultExpectation.params != nil {
		mmInitiateAdminLogon.mock.t.Fatalf("AdminLogonUseCaseMock.InitiateAdminLogon mock is already set by Expect")
	}

	if mmInitiateAdminLogon.defaultExpectation.paramPtrs == nil {
		mmInitiateAdminLogon.defaultExpectation.paramPtrs = &AdminLogonUseCaseMockInitiateAdminLogonParamPtrs{}
	}
	mmInitiateAdminLogon.defaultExpectation.paramPtrs.targetAdminUI = &targetAdminUI
	mmInitiateAdminLogon.defaultExpectation.expectationOrigins.originTargetAdminUI = minimock.CallerInfo(1)

	return mmInitiateAdminLogon
}

// Inspect accepts an inspector function that has same arguments as the AdminLogonUseCase.InitiateAdminLogon
func (mmInitiateAdminLogon *mAdminLogonUseCaseMockInitiateAdminLogon) Inspect(f func(ctx context.Context, localTenantID uuid.UUID, callbackURI string, targetAdminUI string)) *mAdminLogonUseCaseMockInitiateAdminLogon {
	if mmInitiateAdminLogon.mock.inspectFuncInitiateAdminLogon != nil {
		mmInitiateAdminLogon.mock.t.Fatalf("Inspect function is already set for AdminLogonUseCaseMock.InitiateAdminLogon")
	}

	mmInitiateAdminLogon.mock.inspectFuncInitiateAdminLogon = f

	return mmInitiateAdminLogon
}

// Return sets up results that will be returned by AdminLogonUseCase.InitiateAdminLogon
func (mmInitiateAdminLogon *mAdminLogonUseCaseMockInitiateAdminLogon) Return(ip1 *mm_port.InitiateFederatedLoginResponse, err error) *AdminLogonUseCaseMock {
	if mmInitiateAdminLogon.mock.funcInitiateAdminLogon != nil {
		mmInitiateAdminLogon.mock.t.Fatalf("AdminLogonUseCaseMock.InitiateAdminLogon mock is already set by Set")
	}

	if mmInitiateAdminLogon.defaultExpectation == nil {
		mmInitiateAdminLogon.defaultExpectation = &AdminLogonUseCaseMockInitiateAdminLogonExpectation{mock: mmInitiateAdminLogon.mock}
	}
	mmInitiateAdminLogon.defaultExpectation.results = &AdminLogonUseCaseMockInitiateAdminLogonResults{ip1, err}
	mmInitiateAdminLogon.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmInitiateAdminLogon.mock
}

// Set uses given function f to mock the AdminLogonUseCase.InitiateAdminLogon method
func (mmInitiateAdminLogon *mAdminLogonUseCaseMockInitiateAdminLogon) Set(f func(ctx context.Context, localTenantID uuid.UUID, callbackURI string, targetAdminUI string) (ip1 *mm_port.InitiateFederatedLoginResponse, err error)) *AdminLogonUseCaseMock {
	if mmInitiateAdminLogon.defaultExpectation != nil {
		mmInitiateAdminLogon.mock.t.Fatalf("Default expectation is already set for the AdminLogonUseCase.InitiateAdminLogon method")
	}

	if len(mmInitiateAdminLogon.expectations) > 0 {
		mmInitiateAdminLogon.mock.t.Fatalf("Some expectations are already set for the AdminLogonUseCase.InitiateAdminLogon method")
	}

	mmInitiateAdminLogon.mock.funcInitiateAdminLogon = f
	mmInitiateAdminLogon.mock.funcInitiateAdminLogonOrigin = minimock.CallerInfo(1)
	return mmInitiateAdminLogon.mock
}

// When sets expectation for the AdminLogonUseCase.InitiateAdminLogon which will trigger the result defined by the following
// Then helper
func (mmInitiateAdminLogon *mAdminLogonUseCaseMockInitiateAdminLogon) When(ctx context.Context, localTenantID uuid.UUID, callbackURI string, targetAdminUI string) *AdminLogonUseCaseMockInitiateAdminLogonExpectation {
	if mmInitiateAdminLogon.mock.funcInitiateAdminLogon != nil {
		mmInitiateAdminLogon.mock.t.Fatalf("AdminLogonUseCaseMock.InitiateAdminLogon mock is already set by Set")
	}

	expectation := &AdminLogonUseCaseMockInitiateAdminLogonExpectation{
		mock:               mmInitiateAdminLogon.mock,
		params:             &AdminLogonUseCaseMockInitiateAdminLogonParams{ctx, localTenantID, callbackURI, targetAdminUI},
		expectationOrigins: AdminLogonUseCaseMockInitiateAdminLogonExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmInitiateAdminLogon.expectations = append(mmInitiateAdminLogon.expectations, expectation)
	return expectation
}

// Then sets up AdminLogonUseCase.InitiateAdminLogon return parameters for the expectation previously defined by the When method
func (e *AdminLogonUseCaseMockInitiateAdminLogonExpectation) Then(ip1 *mm_port.InitiateFederatedLoginResponse, err error) *AdminLogonUseCaseMock {
	e.results = &AdminLogonUseCaseMockInitiateAdminLogonResults{ip1, err}
	return e.mock
}

// Times sets number of times AdminLogonUseCase.InitiateAdminLogon should be invoked
func (mmInitiateAdminLogon *mAdminLogonUseCaseMockInitiateAdminLogon) Times(n uint64) *mAdminLogonUseCaseMockInitiateAdminLogon {
	if n == 0 {
		mmInitiateAdminLogon.mock.t.Fatalf("Times of AdminLogonUseCaseMock.InitiateAdminLogon mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmInitiateAdminLogon.expectedInvocations, n)
	mmInitiateAdminLogon.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmInitiateAdminLogon
}

func (mmInitiateAdminLogon *mAdminLogonUseCaseMockInitiateAdminLogon) invocationsDone() bool {
	if len(mmInitiateAdminLogon.expectations) == 0 && mmInitiateAdminLogon.defaultExpectation == nil && mmInitiateAdminLogon.mock.funcInitiateAdminLogon == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmInitiateAdminLogon.mock.afterInitiateAdminLogonCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmInitiateAdminLogon.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// InitiateAdminLogon implements mm_port.AdminLogonUseCase
func (mmInitiateAdminLogon *AdminLogonUseCaseMock) InitiateAdminLogon(ctx context.Context, localTenantID uuid.UUID, callbackURI string, targetAdminUI string) (ip1 *mm_port.InitiateFederatedLoginResponse, err error) {
	mm_atomic.AddUint64(&mmInitiateAdminLogon.beforeInitiateAdminLogonCounter, 1)
	defer mm_atomic.AddUint64(&mmInitiateAdminLogon.afterInitiateAdminLogonCounter, 1)

	mmInitiateAdminLogon.t.Helper()

	if mmInitiateAdminLogon.inspectFuncInitiateAdminLogon != nil {
		mmInitiateAdminLogon.inspectFuncInitiateAdminLogon(ctx, localTenantID, callbackURI, targetAdminUI)
	}

	mm_params := AdminLogonUseCaseMockInitiateAdminLogonParams{ctx, localTenantID, callbackURI, targetAdminUI}

	// Record call args
	mmInitiateAdminLogon.InitiateAdminLogonMock.mutex.Lock()
	mmInitiateAdminLogon.InitiateAdminLogonMock.callArgs = append(mmInitiateAdminLogon.InitiateAdminLogonMock.callArgs, &mm_params)
	mmInitiateAdminLogon.InitiateAdminLogonMock.mutex.Unlock()

	for _, e := range mmInitiateAdminLogon.InitiateAdminLogonMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.ip1, e.results.err
		}
	}

	if mmInitiateAdminLogon.InitiateAdminLogonMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmInitiateAdminLogon.InitiateAdminLogonMock.defaultExpectation.Counter, 1)
		mm_want := mmInitiateAdminLogon.InitiateAdminLogonMock.defaultExpectation.params
		mm_want_ptrs := mmInitiateAdminLogon.InitiateAdminLogonMock.defaultExpectation.paramPtrs

		mm_got := AdminLogonUseCaseMockInitiateAdminLogonParams{ctx, localTenantID, callbackURI, targetAdminUI}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmInitiateAdminLogon.t.Errorf("AdminLogonUseCaseMock.InitiateAdminLogon got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmInitiateAdminLogon.InitiateAdminLogonMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.localTenantID != nil && !minimock.Equal(*mm_want_ptrs.localTenantID, mm_got.localTenantID) {
				mmInitiateAdminLogon.t.Errorf("AdminLogonUseCaseMock.InitiateAdminLogon got unexpected parameter localTenantID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmInitiateAdminLogon.InitiateAdminLogonMock.defaultExpectation.expectationOrigins.originLocalTenantID, *mm_want_ptrs.localTenantID, mm_got.localTenantID, minimock.Diff(*mm_want_ptrs.localTenantID, mm_got.localTenantID))
			}

			if mm_want_ptrs.callbackURI != nil && !minimock.Equal(*mm_want_ptrs.callbackURI, mm_got.callbackURI) {
				mmInitiateAdminLogon.t.Errorf("AdminLogonUseCaseMock.InitiateAdminLogon got unexpected parameter callbackURI, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmInitiateAdminLogon.InitiateAdminLogonMock.defaultExpectation.expectationOrigins.originCallbackURI, *mm_want_ptrs.callbackURI, mm_got.callbackURI, minimock.Diff(*mm_want_ptrs.callbackURI, mm_got.callbackURI))
			}

			if mm_want_ptrs.targetAdminUI != nil && !minimock.Equal(*mm_want_ptrs.targetAdminUI, mm_got.targetAdminUI) {
				mmInitiateAdminLogon.t.Errorf("AdminLogonUseCaseMock.InitiateAdminLogon got unexpected parameter targetAdminUI, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmInitiateAdminLogon.InitiateAdminLogonMock.defaultExpectation.expectationOrigins.originTargetAdminUI, *mm_want_ptrs.targetAdminUI, mm_got.targetAdminUI, minimock.Diff(*mm_want_ptrs.targetAdminUI, mm_got.targetAdminUI))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmInitiateAdminLogon.t.Errorf("AdminLogonUseCaseMock.InitiateAdminLogon got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmInitiateAdminLogon.InitiateAdminLogonMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmInitiateAdminLogon.InitiateAdminLogonMock.defaultExpectation.results
		if mm_results == nil {
			mmInitiateAdminLogon.t.Fatal("No results are set for the AdminLogonUseCaseMock.InitiateAdminLogon")
		}
		return (*mm_results).ip1, (*mm_results).err
	}
	if mmInitiateAdminLogon.funcInitiateAdminLogon != nil {
		return mmInitiateAdminLogon.funcInitiateAdminLogon(ctx, localTenantID, callbackURI, targetAdminUI)
	}
	mmInitiateAdminLogon.t.Fatalf("Unexpected call to AdminLogonUseCaseMock.InitiateAdminLogon. %v %v %v %v", ctx, localTenantID, callbackURI, targetAdminUI)
	return
}

// InitiateAdminLogonAfterCounter returns a count of finished AdminLogonUseCaseMock.InitiateAdminLogon invocations
func (mmInitiateAdminLogon *AdminLogonUseCaseMock) InitiateAdminLogonAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmInitiateAdminLogon.afterInitiateAdminLogonCounter)
}

// InitiateAdminLogonBeforeCounter returns a count of AdminLogonUseCaseMock.InitiateAdminLogon invocations
func (mmInitiateAdminLogon *AdminLogonUseCaseMock) InitiateAdminLogonBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmInitiateAdminLogon.beforeInitiateAdminLogonCounter)
}

// Calls returns a list of arguments used in each call to AdminLogonUseCaseMock.InitiateAdminLogon.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmInitiateAdminLogon *mAdminLogonUseCaseMockInitiateAdminLogon) Calls() []*AdminLogonUseCaseMockInitiateAdminLogonParams {
	mmInitiateAdminLogon.mutex.RLock()

	argCopy := make([]*AdminLogonUseCaseMockInitiateAdminLogonParams, len(mmInitiateAdminLogon.callArgs))
	copy(argCopy, mmInitiateAdminLogon.callArgs)

	mmInitiateAdminLogon.mutex.RUnlock()

	return argCopy
}

// MinimockInitiateAdminLogonDone returns true if the count of the InitiateAdminLogon invocations corresponds
// the number of defined expectations
func (m *AdminLogonUseCaseMock) MinimockInitiateAdminLogonDone() bool {
	if m.InitiateAdminLogonMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.InitiateAdminLogonMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.InitiateAdminLogonMock.invocationsDone()
}

// MinimockInitiateAdminLogonInspect logs each unmet expectation
func (m *AdminLogonUseCaseMock) MinimockInitiateAdminLogonInspect() {
	for _, e := range m.InitiateAdminLogonMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to AdminLogonUseCaseMock.InitiateAdminLogon at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterInitiateAdminLogonCounter := mm_atomic.LoadUint64(&m.afterInitiateAdminLogonCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.InitiateAdminLogonMock.defaultExpectation != nil && afterInitiateAdminLogonCounter < 1 {
		if m.InitiateAdminLogonMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to AdminLogonUseCaseMock.InitiateAdminLogon at\n%s", m.InitiateAdminLogonMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to AdminLogonUseCaseMock.InitiateAdminLogon at\n%s with params: %#v", m.InitiateAdminLogonMock.defaultExpectation.expectationOrigins.origin, *m.InitiateAdminLogonMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcInitiateAdminLogon != nil && afterInitiateAdminLogonCounter < 1 {
		m.t.Errorf("Expected call to AdminLogonUseCaseMock.InitiateAdminLogon at\n%s", m.funcInitiateAdminLogonOrigin)
	}

	if !m.InitiateAdminLogonMock.invocationsDone() && afterInitiateAdminLogonCounter > 0 {
		m.t.Errorf("Expected %d calls to AdminLogonUseCaseMock.InitiateAdminLogon at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.InitiateAdminLogonMock.expectedInvocations), m.InitiateAdminLogonMock.expectedInvocationsOrigin, afterInitiateAdminLogonCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *AdminLogonUseCaseMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockCompleteAdminLogonInspect()

			m.MinimockInitiateAdminLogonInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *AdminLogonUseCaseMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *AdminLogonUseCaseMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockCompleteAdminLogonDone() &&
		m.MinimockInitiateAdminLogonDone()
}
