// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package portmock

//go:generate minimock -i sprezz-identity/internal/domain/port.Crypto -o crypto_mock.go -n CryptoMock -p portmock

import (
	"sprezz-identity/internal/domain/model"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// CryptoMock implements mm_port.Crypto
type CryptoMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcSignAccessToken          func(claims model.TokenClaims, alg model.SignatureAlgorithm) (s1 string, err error)
	funcSignAccessTokenOrigin    string
	inspectFuncSignAccessToken   func(claims model.TokenClaims, alg model.SignatureAlgorithm)
	afterSignAccessTokenCounter  uint64
	beforeSignAccessTokenCounter uint64
	SignAccessTokenMock          mCryptoMockSignAccessToken

	funcSignIDToken          func(claims model.OIDCTokenClaims, alg model.SignatureAlgorithm) (s1 string, err error)
	funcSignIDTokenOrigin    string
	inspectFuncSignIDToken   func(claims model.OIDCTokenClaims, alg model.SignatureAlgorithm)
	afterSignIDTokenCounter  uint64
	beforeSignIDTokenCounter uint64
	SignIDTokenMock          mCryptoMockSignIDToken
}

// NewCryptoMock returns a mock for mm_port.Crypto
func NewCryptoMock(t minimock.Tester) *CryptoMock {
	m := &CryptoMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.SignAccessTokenMock = mCryptoMockSignAccessToken{mock: m}
	m.SignAccessTokenMock.callArgs = []*CryptoMockSignAccessTokenParams{}

	m.SignIDTokenMock = mCryptoMockSignIDToken{mock: m}
	m.SignIDTokenMock.callArgs = []*CryptoMockSignIDTokenParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mCryptoMockSignAccessToken struct {
	optional           bool
	mock               *CryptoMock
	defaultExpectation *CryptoMockSignAccessTokenExpectation
	expectations       []*CryptoMockSignAccessTokenExpectation

	callArgs []*CryptoMockSignAccessTokenParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// CryptoMockSignAccessTokenExpectation specifies expectation struct of the Crypto.SignAccessToken
type CryptoMockSignAccessTokenExpectation struct {
	mock               *CryptoMock
	params             *CryptoMockSignAccessTokenParams
	paramPtrs          *CryptoMockSignAccessTokenParamPtrs
	expectationOrigins CryptoMockSignAccessTokenExpectationOrigins
	results            *CryptoMockSignAccessTokenResults
	returnOrigin       string
	Counter            uint64
}

// CryptoMockSignAccessTokenParams contains parameters of the Crypto.SignAccessToken
type CryptoMockSignAccessTokenParams struct {
	claims model.TokenClaims
	alg    model.SignatureAlgorithm
}

// CryptoMockSignAccessTokenParamPtrs contains pointers to parameters of the Crypto.SignAccessToken
type CryptoMockSignAccessTokenParamPtrs struct {
	claims *model.TokenClaims
	alg    *model.SignatureAlgorithm
}

// CryptoMockSignAccessTokenResults contains results of the Crypto.SignAccessToken
type CryptoMockSignAccessTokenResults struct {
	s1  string
	err error
}

// CryptoMockSignAccessTokenOrigins contains origins of expectations of the Crypto.SignAccessToken
type CryptoMockSignAccessTokenExpectationOrigins struct {
	origin       string
	originClaims string
	originAlg    string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmSignAccessToken *mCryptoMockSignAccessToken) Optional() *mCryptoMockSignAccessToken {
	mmSignAccessToken.optional = true
	return mmSignAccessToken
}

// Expect sets up expected params for Crypto.SignAccessToken
func (mmSignAccessToken *mCryptoMockSignAccessToken) Expect(claims model.TokenClaims, alg model.SignatureAlgorithm) *mCryptoMockSignAccessToken {
	if mmSignAccessToken.mock.funcSignAccessToken != nil {
		mmSignAccessToken.mock.t.Fatalf("CryptoMock.SignAccessToken mock is already set by Set")
	}

	if mmSignAccessToken.defaultExpectation == nil {
		mmSignAccessToken.defaultExpectation = &CryptoMockSignAccessTokenExpectation{}
	}

	if mmSignAccessToken.defaultExpectation.paramPtrs != nil {
		mmSignAccessToken.mock.t.Fatalf("CryptoMock.SignAccessToken mock is already set by ExpectParams functions")
	}

	mmSignAccessToken.defaultExpectation.params = &CryptoMockSignAccessTokenParams{claims, alg}
	mmSignAccessToken.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmSignAccessToken.expectations {
		if minimock.Equal(e.params, mmSignAccessToken.defaultExpectation.params) {
			mmSignAccessToken.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmSignAccessToken.defaultExpectation.params)
		}
	}

	return mmSignAccessToken
}

// ExpectClaimsParam1 sets up expected param claims for Crypto.SignAccessToken
func (mmSignAccessToken *mCryptoMockSignAccessToken) ExpectClaimsParam1(claims model.TokenClaims) *mCryptoMockSignAccessToken {
	if mmSignAccessToken.mock.funcSignAccessToken != nil {
		mmSignAccessToken.mock.t.Fatalf("CryptoMock.SignAccessToken mock is already set by Set")
	}

	if mmSignAccessToken.defaultExpectation == nil {
		mmSignAccessToken.defaultExpectation = &CryptoMockSignAccessTokenExpectation{}
	}

	if mmSignAccessToken.defaultExpectation.params != nil {
		mmSignAccessToken.mock.t.Fatalf("CryptoMock.SignAccessToken mock is already set by Expect")
	}

	if mmSignAccessToken.defaultExpectation.paramPtrs == nil {
		mmSignAccessToken.defaultExpectation.paramPtrs = &CryptoMockSignAccessTokenParamPtrs{}
	}
	mmSignAccessToken.defaultExpectation.paramPtrs.claims = &claims
	mmSignAccessToken.defaultExpectation.expectationOrigins.originClaims = minimock.CallerInfo(1)

	return mmSignAccessToken
}

// ExpectAlgParam2 sets up expected param alg for Crypto.SignAccessToken
func (mmSignAccessToken *mCryptoMockSignAccessToken) ExpectAlgParam2(alg model.SignatureAlgorithm) *mCryptoMockSignAccessToken {
	if mmSignAccessToken.mock.funcSignAccessToken != nil {
		mmSignAccessToken.mock.t.Fatalf("CryptoMock.SignAccessToken mock is already set by Set")
	}

	if mmSignAccessToken.defaultExpectation == nil {
		mmSignAccessToken.defaultExpectation = &CryptoMockSignAccessTokenExpectation{}
	}

	if mmSignAccessToken.defaultExpectation.params != nil {
		mmSignAccessToken.mock.t.Fatalf("CryptoMock.SignAccessToken mock is already set by Expect")
	}

	if mmSignAccessToken.defaultExpectation.paramPtrs == nil {
		mmSignAccessToken.defaultExpectation.paramPtrs = &CryptoMockSignAccessTokenParamPtrs{}
	}
	mmSignAccessToken.defaultExpectation.paramPtrs.alg = &alg
	mmSignAccessToken.defaultExpectation.expectationOrigins.originAlg = minimock.CallerInfo(1)

	return mmSignAccessToken
}

// Inspect accepts an inspector function that has same arguments as the Crypto.SignAccessToken
func (mmSignAccessToken *mCryptoMockSignAccessToken) Inspect(f func(claims model.TokenClaims, alg model.SignatureAlgorithm)) *mCryptoMockSignAccessToken {
	if mmSignAccessToken.mock.inspectFuncSignAccessToken != nil {
		mmSignAccessToken.mock.t.Fatalf("Inspect function is already set for CryptoMock.SignAccessToken")
	}

	mmSignAccessToken.mock.inspectFuncSignAccessToken = f

	return mmSignAccessToken
}

// Return sets up results that will be returned by Crypto.SignAccessToken
func (mmSignAccessToken *mCryptoMockSignAccessToken) Return(s1 string, err error) *CryptoMock {
	if mmSignAccessToken.mock.funcSignAccessToken != nil {
		mmSignAccessToken.mock.t.Fatalf("CryptoMock.SignAccessToken mock is already set by Set")
	}

	if mmSignAccessToken.defaultExpectation == nil {
		mmSignAccessToken.defaultExpectation = &CryptoMockSignAccessTokenExpectation{mock: mmSignAccessToken.mock}
	}
	mmSignAccessToken.defaultExpectation.results = &CryptoMockSignAccessTokenResults{s1, err}
	mmSignAccessToken.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmSignAccessToken.mock
}

// Set uses given function f to mock the Crypto.SignAccessToken method
func (mmSignAccessToken *mCryptoMockSignAccessToken) Set(f func(claims model.TokenClaims, alg model.SignatureAlgorithm) (s1 string, err error)) *CryptoMock {
	if mmSignAccessToken.defaultExpectation != nil {
		mmSignAccessToken.mock.t.Fatalf("Default expectation is already set for the Crypto.SignAccessToken method")
	}

	if len(mmSignAccessToken.expectations) > 0 {
		mmSignAccessToken.mock.t.Fatalf("Some expectations are already set for the Crypto.SignAccessToken method")
	}

	mmSignAccessToken.mock.funcSignAccessToken = f
	mmSignAccessToken.mock.funcSignAccessTokenOrigin = minimock.CallerInfo(1)
	return mmSignAccessToken.mock
}

// When sets expectation for the Crypto.SignAccessToken which will trigger the result defined by the following
// Then helper
func (mmSignAccessToken *mCryptoMockSignAccessToken) When(claims model.TokenClaims, alg model.SignatureAlgorithm) *CryptoMockSignAccessTokenExpectation {
	if mmSignAccessToken.mock.funcSignAccessToken != nil {
		mmSignAccessToken.mock.t.Fatalf("CryptoMock.SignAccessToken mock is already set by Set")
	}

	expectation := &CryptoMockSignAccessTokenExpectation{
		mock:               mmSignAccessToken.mock,
		params:             &CryptoMockSignAccessTokenParams{claims, alg},
		expectationOrigins: CryptoMockSignAccessTokenExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmSignAccessToken.expectations = append(mmSignAccessToken.expectations, expectation)
	return expectation
}

// Then sets up Crypto.SignAccessToken return parameters for the expectation previously defined by the When method
func (e *CryptoMockSignAccessTokenExpectation) Then(s1 string, err error) *CryptoMock {
	e.results = &CryptoMockSignAccessTokenResults{s1, err}
	return e.mock
}

// Times sets number of times Crypto.SignAccessToken should be invoked
func (mmSignAccessToken *mCryptoMockSignAccessToken) Times(n uint64) *mCryptoMockSignAccessToken {
	if n == 0 {
		mmSignAccessToken.mock.t.Fatalf("Times of CryptoMock.SignAccessToken mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmSignAccessToken.expectedInvocations, n)
	mmSignAccessToken.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmSignAccessToken
}

func (mmSignAccessToken *mCryptoMockSignAccessToken) invocationsDone() bool {
	if len(mmSignAccessToken.expectations) == 0 && mmSignAccessToken.defaultExpectation == nil && mmSignAccessToken.mock.funcSignAccessToken == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmSignAccessToken.mock.afterSignAccessTokenCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmSignAccessToken.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// SignAccessToken implements mm_port.Crypto
func (mmSignAccessToken *CryptoMock) SignAccessToken(claims model.TokenClaims, alg model.SignatureAlgorithm) (s1 string, err error) {
	mm_atomic.AddUint64(&mmSignAccessToken.beforeSignAccessTokenCounter, 1)
	defer mm_atomic.AddUint64(&mmSignAccessToken.afterSignAccessTokenCounter, 1)

	mmSignAccessToken.t.Helper()

	if mmSignAccessToken.inspectFuncSignAccessToken != nil {
		mmSignAccessToken.inspectFuncSignAccessToken(claims, alg)
	}

	mm_params := CryptoMockSignAccessTokenParams{claims, alg}

	// Record call args
	mmSignAccessToken.SignAccessTokenMock.mutex.Lock()
	mmSignAccessToken.SignAccessTokenMock.callArgs = append(mmSignAccessToken.SignAccessTokenMock.callArgs, &mm_params)
	mmSignAccessToken.SignAccessTokenMock.mutex.Unlock()

	for _, e := range mmSignAccessToken.SignAccessTokenMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.s1, e.results.err
		}
	}

	if mmSignAccessToken.SignAccessTokenMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmSignAccessToken.SignAccessTokenMock.defaultExpectation.Counter, 1)
		mm_want := mmSignAccessToken.SignAccessTokenMock.defaultExpectation.params
		mm_want_ptrs := mmSignAccessToken.SignAccessTokenMock.defaultExpectation.paramPtrs

		mm_got := CryptoMockSignAccessTokenParams{claims, alg}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.claims != nil && !minimock.Equal(*mm_want_ptrs.claims, mm_got.claims) {
				mmSignAccessToken.t.Errorf("CryptoMock.SignAccessToken got unexpected parameter claims, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmSignAccessToken.SignAccessTokenMock.defaultExpectation.expectationOrigins.originClaims, *mm_want_ptrs.claims, mm_got.claims, minimock.Diff(*mm_want_ptrs.claims, mm_got.claims))
			}

			if mm_want_ptrs.alg != nil && !minimock.Equal(*mm_want_ptrs.alg, mm_got.alg) {
				mmSignAccessToken.t.Errorf("CryptoMock.SignAccessToken got unexpected parameter alg, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmSignAccessToken.SignAccessTokenMock.defaultExpectation.expectationOrigins.originAlg, *mm_want_ptrs.alg, mm_got.alg, minimock.Diff(*mm_want_ptrs.alg, mm_got.alg))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmSignAccessToken.t.Errorf("CryptoMock.SignAccessToken got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmSignAccessToken.SignAccessTokenMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmSignAccessToken.SignAccessTokenMock.defaultExpectation.results
		if mm_results == nil {
			mmSignAccessToken.t.Fatal("No results are set for the CryptoMock.SignAccessToken")
		}
		return (*mm_results).s1, (*mm_results).err
	}
	if mmSignAccessToken.funcSignAccessToken != nil {
		return mmSignAccessToken.funcSignAccessToken(claims, alg)
	}
	mmSignAccessToken.t.Fatalf("Unexpected call to CryptoMock.SignAccessToken. %v %v", claims, alg)
	return
}

// SignAccessTokenAfterCounter returns a count of finished CryptoMock.SignAccessToken invocations
func (mmSignAccessToken *CryptoMock) SignAccessTokenAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSignAccessToken.afterSignAccessTokenCounter)
}

// SignAccessTokenBeforeCounter returns a count of CryptoMock.SignAccessToken invocations
func (mmSignAccessToken *CryptoMock) SignAccessTokenBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSignAccessToken.beforeSignAccessTokenCounter)
}

// Calls returns a list of arguments used in each call to CryptoMock.SignAccessToken.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmSignAccessToken *mCryptoMockSignAccessToken) Calls() []*CryptoMockSignAccessTokenParams {
	mmSignAccessToken.mutex.RLock()

	argCopy := make([]*CryptoMockSignAccessTokenParams, len(mmSignAccessToken.callArgs))
	copy(argCopy, mmSignAccessToken.callArgs)

	mmSignAccessToken.mutex.RUnlock()

	return argCopy
}

// MinimockSignAccessTokenDone returns true if the count of the SignAccessToken invocations corresponds
// the number of defined expectations
func (m *CryptoMock) MinimockSignAccessTokenDone() bool {
	if m.SignAccessTokenMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.SignAccessTokenMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.SignAccessTokenMock.invocationsDone()
}

// MinimockSignAccessTokenInspect logs each unmet expectation
func (m *CryptoMock) MinimockSignAccessTokenInspect() {
	for _, e := range m.SignAccessTokenMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to CryptoMock.SignAccessToken at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterSignAccessTokenCounter := mm_atomic.LoadUint64(&m.afterSignAccessTokenCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.SignAccessTokenMock.defaultExpectation != nil && afterSignAccessTokenCounter < 1 {
		if m.SignAccessTokenMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to CryptoMock.SignAccessToken at\n%s", m.SignAccessTokenMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to CryptoMock.SignAccessToken at\n%s with params: %#v", m.SignAccessTokenMock.defaultExpectation.expectationOrigins.origin, *m.SignAccessTokenMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcSignAccessToken != nil && afterSignAccessTokenCounter < 1 {
		m.t.Errorf("Expected call to CryptoMock.SignAccessToken at\n%s", m.funcSignAccessTokenOrigin)
	}

	if !m.SignAccessTokenMock.invocationsDone() && afterSignAccessTokenCounter > 0 {
		m.t.Errorf("Expected %d calls to CryptoMock.SignAccessToken at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.SignAccessTokenMock.expectedInvocations), m.SignAccessTokenMock.expectedInvocationsOrigin, afterSignAccessTokenCounter)
	}
}

type mCryptoMockSignIDToken struct {
	optional           bool
	mock               *CryptoMock
	defaultExpectation *CryptoMockSignIDTokenExpectation
	expectations       []*CryptoMockSignIDTokenExpectation

	callArgs []*CryptoMockSignIDTokenParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// CryptoMockSignIDTokenExpectation specifies expectation struct of the Crypto.SignIDToken
type CryptoMockSignIDTokenExpectation struct {
	mock               *CryptoMock
	params             *CryptoMockSignIDTokenParams
	paramPtrs          *CryptoMockSignIDTokenParamPtrs
	expectationOrigins CryptoMockSignIDTokenExpectationOrigins
	results            *CryptoMockSignIDTokenResults
	returnOrigin       string
	Counter            uint64
}

// CryptoMockSignIDTokenParams contains parameters of the Crypto.SignIDToken
type CryptoMockSignIDTokenParams struct {
	claims model.OIDCTokenClaims
	alg    model.SignatureAlgorithm
}

// CryptoMockSignIDTokenParamPtrs contains pointers to parameters of the Crypto.SignIDToken
type CryptoMockSignIDTokenParamPtrs struct {
	claims *model.OIDCTokenClaims
	alg    *model.SignatureAlgorithm
}

// CryptoMockSignIDTokenResults contains results of the Crypto.SignIDToken
type CryptoMockSignIDTokenResults struct {
	s1  string
	err error
}

// CryptoMockSignIDTokenOrigins contains origins of expectations of the Crypto.SignIDToken
type CryptoMockSignIDTokenExpectationOrigins struct {
	origin       string
	originClaims string
	originAlg    string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmSignIDToken *mCryptoMockSignIDToken) Optional() *mCryptoMockSignIDToken {
	mmSignIDToken.optional = true
	return mmSignIDToken
}

// Expect sets up expected params for Crypto.SignIDToken
func (mmSignIDToken *mCryptoMockSignIDToken) Expect(claims model.OIDCTokenClaims, alg model.SignatureAlgorithm) *mCryptoMockSignIDToken {
	if mmSignIDToken.mock.funcSignIDToken != nil {
		mmSignIDToken.mock.t.Fatalf("CryptoMock.SignIDToken mock is already set by Set")
	}

	if mmSignIDToken.defaultExpectation == nil {
		mmSignIDToken.defaultExpectation = &CryptoMockSignIDTokenExpectation{}
	}

	if mmSignIDToken.defaultExpectation.paramPtrs != nil {
		mmSignIDToken.mock.t.Fatalf("CryptoMock.SignIDToken mock is already set by ExpectParams functions")
	}

	mmSignIDToken.defaultExpectation.params = &CryptoMockSignIDTokenParams{claims, alg}
	mmSignIDToken.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmSignIDToken.expectations {
		if minimock.Equal(e.params, mmSignIDToken.defaultExpectation.params) {
			mmSignIDToken.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmSignIDToken.defaultExpectation.params)
		}
	}

	return mmSignIDToken
}

// ExpectClaimsParam1 sets up expected param claims for Crypto.SignIDToken
func (mmSignIDToken *mCryptoMockSignIDToken) ExpectClaimsParam1(claims model.OIDCTokenClaims) *mCryptoMockSignIDToken {
	if mmSignIDToken.mock.funcSignIDToken != nil {
		mmSignIDToken.mock.t.Fatalf("CryptoMock.SignIDToken mock is already set by Set")
	}

	if mmSignIDToken.defaultExpectation == nil {
		mmSignIDToken.defaultExpectation = &CryptoMockSignIDTokenExpectation{}
	}

	if mmSignIDToken.defaultExpectation.params != nil {
		mmSignIDToken.mock.t.Fatalf("CryptoMock.SignIDToken mock is already set by Expect")
	}

	if mmSignIDToken.defaultExpectation.paramPtrs == nil {
		mmSignIDToken.defaultExpectation.paramPtrs = &CryptoMockSignIDTokenParamPtrs{}
	}
	mmSignIDToken.defaultExpectation.paramPtrs.claims = &claims
	mmSignIDToken.defaultExpectation.expectationOrigins.originClaims = minimock.CallerInfo(1)

	return mmSignIDToken
}

// ExpectAlgParam2 sets up expected param alg for Crypto.SignIDToken
func (mmSignIDToken *mCryptoMockSignIDToken) ExpectAlgParam2(alg model.SignatureAlgorithm) *mCryptoMockSignIDToken {
	if mmSignIDToken.mock.funcSignIDToken != nil {
		mmSignIDToken.mock.t.Fatalf("CryptoMock.SignIDToken mock is already set by Set")
	}

	if mmSignIDToken.defaultExpectation == nil {
		mmSignIDToken.defaultExpectation = &CryptoMockSignIDTokenExpectation{}
	}

	if mmSignIDToken.defaultExpectation.params != nil {
		mmSignIDToken.mock.t.Fatalf("CryptoMock.SignIDToken mock is already set by Expect")
	}

	if mmSignIDToken.defaultExpectation.paramPtrs == nil {
		mmSignIDToken.defaultExpectation.paramPtrs = &CryptoMockSignIDTokenParamPtrs{}
	}
	mmSignIDToken.defaultExpectation.paramPtrs.alg = &alg
	mmSignIDToken.defaultExpectation.expectationOrigins.originAlg = minimock.CallerInfo(1)

	return mmSignIDToken
}

// Inspect accepts an inspector function that has same arguments as the Crypto.SignIDToken
func (mmSignIDToken *mCryptoMockSignIDToken) Inspect(f func(claims model.OIDCTokenClaims, alg model.SignatureAlgorithm)) *mCryptoMockSignIDToken {
	if mmSignIDToken.mock.inspectFuncSignIDToken != nil {
		mmSignIDToken.mock.t.Fatalf("Inspect function is already set for CryptoMock.SignIDToken")
	}

	mmSignIDToken.mock.inspectFuncSignIDToken = f

	return mmSignIDToken
}

// Return sets up results that will be returned by Crypto.SignIDToken
func (mmSignIDToken *mCryptoMockSignIDToken) Return(s1 string, err error) *CryptoMock {
	if mmSignIDToken.mock.funcSignIDToken != nil {
		mmSignIDToken.mock.t.Fatalf("CryptoMock.SignIDToken mock is already set by Set")
	}

	if mmSignIDToken.defaultExpectation == nil {
		mmSignIDToken.defaultExpectation = &CryptoMockSignIDTokenExpectation{mock: mmSignIDToken.mock}
	}
	mmSignIDToken.defaultExpectation.results = &CryptoMockSignIDTokenResults{s1, err}
	mmSignIDToken.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmSignIDToken.mock
}

// Set uses given function f to mock the Crypto.SignIDToken method
func (mmSignIDToken *mCryptoMockSignIDToken) Set(f func(claims model.OIDCTokenClaims, alg model.SignatureAlgorithm) (s1 string, err error)) *CryptoMock {
	if mmSignIDToken.defaultExpectation != nil {
		mmSignIDToken.mock.t.Fatalf("Default expectation is already set for the Crypto.SignIDToken method")
	}

	if len(mmSignIDToken.expectations) > 0 {
		mmSignIDToken.mock.t.Fatalf("Some expectations are already set for the Crypto.SignIDToken method")
	}

	mmSignIDToken.mock.funcSignIDToken = f
	mmSignIDToken.mock.funcSignIDTokenOrigin = minimock.CallerInfo(1)
	return mmSignIDToken.mock
}

// When sets expectation for the Crypto.SignIDToken which will trigger the result defined by the following
// Then helper
func (mmSignIDToken *mCryptoMockSignIDToken) When(claims model.OIDCTokenClaims, alg model.SignatureAlgorithm) *CryptoMockSignIDTokenExpectation {
	if mmSignIDToken.mock.funcSignIDToken != nil {
		mmSignIDToken.mock.t.Fatalf("CryptoMock.SignIDToken mock is already set by Set")
	}

	expectation := &CryptoMockSignIDTokenExpectation{
		mock:               mmSignIDToken.mock,
		params:             &CryptoMockSignIDTokenParams{claims, alg},
		expectationOrigins: CryptoMockSignIDTokenExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmSignIDToken.expectations = append(mmSignIDToken.expectations, expectation)
	return expectation
}

// Then sets up Crypto.SignIDToken return parameters for the expectation previously defined by the When method
func (e *CryptoMockSignIDTokenExpectation) Then(s1 string, err error) *CryptoMock {
	e.results = &CryptoMockSignIDTokenResults{s1, err}
	return e.mock
}

// Times sets number of times Crypto.SignIDToken should be invoked
func (mmSignIDToken *mCryptoMockSignIDToken) Times(n uint64) *mCryptoMockSignIDToken {
	if n == 0 {
		mmSignIDToken.mock.t.Fatalf("Times of CryptoMock.SignIDToken mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmSignIDToken.expectedInvocations, n)
	mmSignIDToken.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmSignIDToken
}

func (mmSignIDToken *mCryptoMockSignIDToken) invocationsDone() bool {
	if len(mmSignIDToken.expectations) == 0 && mmSignIDToken.defaultExpectation == nil && mmSignIDToken.mock.funcSignIDToken == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmSignIDToken.mock.afterSignIDTokenCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmSignIDToken.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// SignIDToken implements mm_port.Crypto
func (mmSignIDToken *CryptoMock) SignIDToken(claims model.OIDCTokenClaims, alg model.SignatureAlgorithm) (s1 string, err error) {
	mm_atomic.AddUint64(&mmSignIDToken.beforeSignIDTokenCounter, 1)
	defer mm_atomic.AddUint64(&mmSignIDToken.afterSignIDTokenCounter, 1)

	mmSignIDToken.t.Helper()

	if mmSignIDToken.inspectFuncSignIDToken != nil {
		mmSignIDToken.inspectFuncSignIDToken(claims, alg)
	}

	mm_params := CryptoMockSignIDTokenParams{claims, alg}

	// Record call args
	mmSignIDToken.SignIDTokenMock.mutex.Lock()
	mmSignIDToken.SignIDTokenMock.callArgs = append(mmSignIDToken.SignIDTokenMock.callArgs, &mm_params)
	mmSignIDToken.SignIDTokenMock.mutex.Unlock()

	for _, e := range mmSignIDToken.SignIDTokenMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.s1, e.results.err
		}
	}

	if mmSignIDToken.SignIDTokenMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmSignIDToken.SignIDTokenMock.defaultExpectation.Counter, 1)
		mm_want := mmSignIDToken.SignIDTokenMock.defaultExpectation.params
		mm_want_ptrs := mmSignIDToken.SignIDTokenMock.defaultExpectation.paramPtrs

		mm_got := CryptoMockSignIDTokenParams{claims, alg}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.claims != nil && !minimock.Equal(*mm_want_ptrs.claims, mm_got.claims) {
				mmSignIDToken.t.Errorf("CryptoMock.SignIDToken got unexpected parameter claims, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmSignIDToken.SignIDTokenMock.defaultExpectation.expectationOrigins.originClaims, *mm_want_ptrs.claims, mm_got.claims, minimock.Diff(*mm_want_ptrs.claims, mm_got.claims))
			}

			if mm_want_ptrs.alg != nil && !minimock.Equal(*mm_want_ptrs.alg, mm_got.alg) {
				mmSignIDToken.t.Errorf("CryptoMock.SignIDToken got unexpected parameter alg, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmSignIDToken.SignIDTokenMock.defaultExpectation.expectationOrigins.originAlg, *mm_want_ptrs.alg, mm_got.alg, minimock.Diff(*mm_want_ptrs.alg, mm_got.alg))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmSignIDToken.t.Errorf("CryptoMock.SignIDToken got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmSignIDToken.SignIDTokenMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmSignIDToken.SignIDTokenMock.defaultExpectation.results
		if mm_results == nil {
			mmSignIDToken.t.Fatal("No results are set for the CryptoMock.SignIDToken")
		}
		return (*mm_results).s1, (*mm_results).err
	}
	if mmSignIDToken.funcSignIDToken != nil {
		return mmSignIDToken.funcSignIDToken(claims, alg)
	}
	mmSignIDToken.t.Fatalf("Unexpected call to CryptoMock.SignIDToken. %v %v", claims, alg)
	return
}

// SignIDTokenAfterCounter returns a count of finished CryptoMock.SignIDToken invocations
func (mmSignIDToken *CryptoMock) SignIDTokenAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSignIDToken.afterSignIDTokenCounter)
}

// SignIDTokenBeforeCounter returns a count of CryptoMock.SignIDToken invocations
func (mmSignIDToken *CryptoMock) SignIDTokenBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSignIDToken.beforeSignIDTokenCounter)
}

// Calls returns a list of arguments used in each call to CryptoMock.SignIDToken.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmSignIDToken *mCryptoMockSignIDToken) Calls() []*CryptoMockSignIDTokenParams {
	mmSignIDToken.mutex.RLock()

	argCopy := make([]*CryptoMockSignIDTokenParams, len(mmSignIDToken.callArgs))
	copy(argCopy, mmSignIDToken.callArgs)

	mmSignIDToken.mutex.RUnlock()

	return argCopy
}

// MinimockSignIDTokenDone returns true if the count of the SignIDToken invocations corresponds
// the number of defined expectations
func (m *CryptoMock) MinimockSignIDTokenDone() bool {
	if m.SignIDTokenMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.SignIDTokenMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.SignIDTokenMock.invocationsDone()
}

// MinimockSignIDTokenInspect logs each unmet expectation
func (m *CryptoMock) MinimockSignIDTokenInspect() {
	for _, e := range m.SignIDTokenMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to CryptoMock.SignIDToken at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterSignIDTokenCounter := mm_atomic.LoadUint64(&m.afterSignIDTokenCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.SignIDTokenMock.defaultExpectation != nil && afterSignIDTokenCounter < 1 {
		if m.SignIDTokenMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to CryptoMock.SignIDToken at\n%s", m.SignIDTokenMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to CryptoMock.SignIDToken at\n%s with params: %#v", m.SignIDTokenMock.defaultExpectation.expectationOrigins.origin, *m.SignIDTokenMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcSignIDToken != nil && afterSignIDTokenCounter < 1 {
		m.t.Errorf("Expected call to CryptoMock.SignIDToken at\n%s", m.funcSignIDTokenOrigin)
	}

	if !m.SignIDTokenMock.invocationsDone() && afterSignIDTokenCounter > 0 {
		m.t.Errorf("Expected %d calls to CryptoMock.SignIDToken at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.SignIDTokenMock.expectedInvocations), m.SignIDTokenMock.expectedInvocationsOrigin, afterSignIDTokenCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *CryptoMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockSignAccessTokenInspect()

			m.MinimockSignIDTokenInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *CryptoMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *CryptoMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockSignAccessTokenDone() &&
		m.MinimockSignIDTokenDone()
}
