// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package portmock

//go:generate minimock -i sprezz-identity/internal/domain/port.FederatedLoginUseCase -o federated_login_usecase_mock.go -n FederatedLoginUseCaseMock -p portmock

import (
	"context"
	mm_port "sprezz-identity/internal/domain/port"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// FederatedLoginUseCaseMock implements mm_port.FederatedLoginUseCase
type FederatedLoginUseCaseMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcExecuteFederatedCallback          func(ctx context.Context, cmd mm_port.FederatedCallbackCommand) (fp1 *mm_port.FederatedCallbackResponse, err error)
	funcExecuteFederatedCallbackOrigin    string
	inspectFuncExecuteFederatedCallback   func(ctx context.Context, cmd mm_port.FederatedCallbackCommand)
	afterExecuteFederatedCallbackCounter  uint64
	beforeExecuteFederatedCallbackCounter uint64
	ExecuteFederatedCallbackMock          mFederatedLoginUseCaseMockExecuteFederatedCallback

	funcInitiateFederatedLogin          func(ctx context.Context, cmd mm_port.InitiateFederatedLoginCommand) (ip1 *mm_port.InitiateFederatedLoginResponse, err error)
	funcInitiateFederatedLoginOrigin    string
	inspectFuncInitiateFederatedLogin   func(ctx context.Context, cmd mm_port.InitiateFederatedLoginCommand)
	afterInitiateFederatedLoginCounter  uint64
	beforeInitiateFederatedLoginCounter uint64
	InitiateFederatedLoginMock          mFederatedLoginUseCaseMockInitiateFederatedLogin
}

// NewFederatedLoginUseCaseMock returns a mock for mm_port.FederatedLoginUseCase
func NewFederatedLoginUseCaseMock(t minimock.Tester) *FederatedLoginUseCaseMock {
	m := &FederatedLoginUseCaseMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.ExecuteFederatedCallbackMock = mFederatedLoginUseCaseMockExecuteFederatedCallback{mock: m}
	m.ExecuteFederatedCallbackMock.callArgs = []*FederatedLoginUseCaseMockExecuteFederatedCallbackParams{}

	m.InitiateFederatedLoginMock = mFederatedLoginUseCaseMockInitiateFederatedLogin{mock: m}
	m.InitiateFederatedLoginMock.callArgs = []*FederatedLoginUseCaseMockInitiateFederatedLoginParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mFederatedLoginUseCaseMockExecuteFederatedCallback struct {
	optional           bool
	mock               *FederatedLoginUseCaseMock
	defaultExpectation *FederatedLoginUseCaseMockExecuteFederatedCallbackExpectation
	expectations       []*FederatedLoginUseCaseMockExecuteFederatedCallbackExpectation

	callArgs []*FederatedLoginUseCaseMockExecuteFederatedCallbackParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// FederatedLoginUseCaseMockExecuteFederatedCallbackExpectation specifies expectation struct of the FederatedLoginUseCase.ExecuteFederatedCallback
type FederatedLoginUseCaseMockExecuteFederatedCallbackExpectation struct {
	mock               *FederatedLoginUseCaseMock
	params             *FederatedLoginUseCaseMockExecuteFederatedCallbackParams
	paramPtrs          *FederatedLoginUseCaseMockExecuteFederatedCallbackParamPtrs
	expectationOrigins FederatedLoginUseCaseMockExecuteFederatedCallbackExpectationOrigins
	results            *FederatedLoginUseCaseMockExecuteFederatedCallbackResults
	returnOrigin       string
	Counter            uint64
}

// FederatedLoginUseCaseMockExecuteFederatedCallbackParams contains parameters of the FederatedLoginUseCase.ExecuteFederatedCallback
type FederatedLoginUseCaseMockExecuteFederatedCallbackParams struct {
	ctx context.Context
	cmd mm_port.FederatedCallbackCommand
}

// FederatedLoginUseCaseMockExecuteFederatedCallbackParamPtrs contains pointers to parameters of the FederatedLoginUseCase.ExecuteFederatedCallback
type FederatedLoginUseCaseMockExecuteFederatedCallbackParamPtrs struct {
	ctx *context.Context
	cmd *mm_port.FederatedCallbackCommand
}

// FederatedLoginUseCaseMockExecuteFederatedCallbackResults contains results of the FederatedLoginUseCase.ExecuteFederatedCallback
type FederatedLoginUseCaseMockExecuteFederatedCallbackResults struct {
	fp1 *mm_port.FederatedCallbackResponse
	err error
}

// FederatedLoginUseCaseMockExecuteFederatedCallbackOrigins contains origins of expectations of the FederatedLoginUseCase.ExecuteFederatedCallback
type FederatedLoginUseCaseMockExecuteFederatedCallbackExpectationOrigins struct {
	origin    string
	originCtx string
	originCmd string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmExecuteFederatedCallback *mFederatedLoginUseCaseMockExecuteFederatedCallback) Optional() *mFederatedLoginUseCaseMockExecuteFederatedCallback {
	mmExecuteFederatedCallback.optional = true
	return mmExecuteFederatedCallback
}

// Expect sets up expected params for FederatedLoginUseCase.ExecuteFederatedCallback
func (mmExecuteFederatedCallback *mFederatedLoginUseCaseMockExecuteFederatedCallback) Expect(ctx context.Context, cmd mm_port.FederatedCallbackCommand) *mFederatedLoginUseCaseMockExecuteFederatedCallback {
	if mmExecuteFederatedCallback.mock.funcExecuteFederatedCallback != nil {
		mmExecuteFederatedCallback.mock.t.Fatalf("FederatedLoginUseCaseMock.ExecuteFederatedCallback mock is already set by Set")
	}

	if mmExecuteFederatedCallback.defaultExpectation == nil {
		mmExecuteFederatedCallback.defaultExpectation = &FederatedLoginUseCaseMockExecuteFederatedCallbackExpectation{}
	}

	if mmExecuteFederatedCallback.defaultExpectation.paramPtrs != nil {
		mmExecuteFederatedCallback.mock.t.Fatalf("FederatedLoginUseCaseMock.ExecuteFederatedCallback mock is already set by ExpectParams functions")
	}

	mmExecuteFederatedCallback.defaultExpectation.params = &FederatedLoginUseCaseMockExecuteFederatedCallbackParams{ctx, cmd}
	mmExecuteFederatedCallback.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmExecuteFederatedCallback.expectations {
		if minimock.Equal(e.params, mmExecuteFederatedCallback.defaultExpectation.params) {
			mmExecuteFederatedCallback.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmExecuteFederatedCallback.defaultExpectation.params)
		}
	}

	return mmExecuteFederatedCallback
}

// ExpectCtxParam1 sets up expected param ctx for FederatedLoginUseCase.ExecuteFederatedCallback
func (mmExecuteFederatedCallback *mFederatedLoginUseCaseMockExecuteFederatedCallback) ExpectCtxParam1(ctx context.Context) *mFederatedLoginUseCaseMockExecuteFederatedCallback {
	if mmExecuteFederatedCallback.mock.funcExecuteFederatedCallback != nil {
		mmExecuteFederatedCallback.mock.t.Fatalf("FederatedLoginUseCaseMock.ExecuteFederatedCallback mock is already set by Set")
	}

	if mmExecuteFederatedCallback.defaultExpectation == nil {
		mmExecuteFederatedCallback.defaultExpectation = &FederatedLoginUseCaseMockExecuteFederatedCallbackExpectation{}
	}

	if mmExecuteFederatedCallback.defaultExpectation.params != nil {
		mmExecuteFederatedCallback.mock.t.Fatalf("FederatedLoginUseCaseMock.ExecuteFederatedCallback mock is already set by Expect")
	}

	if mmExecuteFederatedCallback.defaultExpectation.paramPtrs == nil {
		mmExecuteFederatedCallback.defaultExpectation.paramPtrs = &FederatedLoginUseCaseMockExecuteFederatedCallbackParamPtrs{}
	}
	mmExecuteFederatedCallback.defaultExpectation.paramPtrs.ctx = &ctx
	mmExecuteFederatedCallback.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmExecuteFederatedCallback
}

// ExpectCmdParam2 sets up expected param cmd for FederatedLoginUseCase.ExecuteFederatedCallback
func (mmExecuteFederatedCallback *mFederatedLoginUseCaseMockExecuteFederatedCallback) ExpectCmdParam2(cmd mm_port.FederatedCallbackCommand) *mFederatedLoginUseCaseMockExecuteFederatedCallback {
	if mmExecuteFederatedCallback.mock.funcExecuteFederatedCallback != nil {
		mmExecuteFederatedCallback.mock.t.Fatalf("FederatedLoginUseCaseMock.ExecuteFederatedCallback mock is already set by Set")
	}

	if mmExecuteFederatedCallback.defaultExpectation == nil {
		mmExecuteFederatedCallback.defaultExpectation = &FederatedLoginUseCaseMockExecuteFederatedCallbackExpectation{}
	}

	if mmExecuteFederatedCallback.defaultExpectation.params != nil {
		mmExecuteFederatedCallback.mock.t.Fatalf("FederatedLoginUseCaseMock.ExecuteFederatedCallback mock is already set by Expect")
	}

	if mmExecuteFederatedCallback.defaultExpectation.paramPtrs == nil {
		mmExecuteFederatedCallback.defaultExpectation.paramPtrs = &FederatedLoginUseCaseMockExecuteFederatedCallbackParamPtrs{}
	}
	mmExecuteFederatedCallback.defaultExpectation.paramPtrs.cmd = &cmd
	mmExecuteFederatedCallback.defaultExpectation.expectationOrigins.originCmd = minimock.CallerInfo(1)

	return mmExecuteFederatedCallback
}

// Inspect accepts an inspector function that has same arguments as the FederatedLoginUseCase.ExecuteFederatedCallback
func (mmExecuteFederatedCallback *mFederatedLoginUseCaseMockExecuteFederatedCallback) Inspect(f func(ctx context.Context, cmd mm_port.FederatedCallbackCommand)) *mFederatedLoginUseCaseMockExecuteFederatedCallback {
	if mmExecuteFederatedCallback.mock.inspectFuncExecuteFederatedCallback != nil {
		mmExecuteFederatedCallback.mock.t.Fatalf("Inspect function is already set for FederatedLoginUseCaseMock.ExecuteFederatedCallback")
	}

	mmExecuteFederatedCallback.mock.inspectFuncExecuteFederatedCallback = f

	return mmExecuteFederatedCallback
}

// Return sets up results that will be returned by FederatedLoginUseCase.ExecuteFederatedCallback
func (mmExecuteFederatedCallback *mFederatedLoginUseCaseMockExecuteFederatedCallback) Return(fp1 *mm_port.FederatedCallbackResponse, err error) *FederatedLoginUseCaseMock {
	if mmExecuteFederatedCallback.mock.funcExecuteFederatedCallback != nil {
		mmExecuteFederatedCallback.mock.t.Fatalf("FederatedLoginUseCaseMock.ExecuteFederatedCallback mock is already set by Set")
	}

	if mmExecuteFederatedCallback.defaultExpectation == nil {
		mmExecuteFederatedCallback.defaultExpectation = &FederatedLoginUseCaseMockExecuteFederatedCallbackExpectation{mock: mmExecuteFederatedCallback.mock}
	}
	mmExecuteFederatedCallback.defaultExpectation.results = &FederatedLoginUseCaseMockExecuteFederatedCallbackResults{fp1, err}
	mmExecuteFederatedCallback.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmExecuteFederatedCallback.mock
}

// Set uses given function f to mock the FederatedLoginUseCase.ExecuteFederatedCallback method
func (mmExecuteFederatedCallback *mFederatedLoginUseCaseMockExecuteFederatedCallback) Set(f func(ctx context.Context, cmd mm_port.FederatedCallbackCommand) (fp1 *mm_port.FederatedCallbackResponse, err error)) *FederatedLoginUseCaseMock {
	if mmExecuteFederatedCallback.defaultExpectation != nil {
		mmExecuteFederatedCallback.mock.t.Fatalf("Default expectation is already set for the FederatedLoginUseCase.ExecuteFederatedCallback method")
	}

	if len(mmExecuteFederatedCallback.expectations) > 0 {
		mmExecuteFederatedCallback.mock.t.Fatalf("Some expectations are already set for the FederatedLoginUseCase.ExecuteFederatedCallback method")
	}

	mmExecuteFederatedCallback.mock.funcExecuteFederatedCallback = f
	mmExecuteFederatedCallback.mock.funcExecuteFederatedCallbackOrigin = minimock.CallerInfo(1)
	return mmExecuteFederatedCallback.mock
}

// When sets expectation for the FederatedLoginUseCase.ExecuteFederatedCallback which will trigger the result defined by the following
// Then helper
func (mmExecuteFederatedCallback *mFederatedLoginUseCaseMockExecuteFederatedCallback) When(ctx context.Context, cmd mm_port.FederatedCallbackCommand) *FederatedLoginUseCaseMockExecuteFederatedCallbackExpectation {
	if mmExecuteFederatedCallback.mock.funcExecuteFederatedCallback != nil {
		mmExecuteFederatedCallback.mock.t.Fatalf("FederatedLoginUseCaseMock.ExecuteFederatedCallback mock is already set by Set")
	}

	expectation := &FederatedLoginUseCaseMockExecuteFederatedCallbackExpectation{
		mock:               mmExecuteFederatedCallback.mock,
		params:             &FederatedLoginUseCaseMockExecuteFederatedCallbackParams{ctx, cmd},
		expectationOrigins: FederatedLoginUseCaseMockExecuteFederatedCallbackExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmExecuteFederatedCallback.expectations = append(mmExecuteFederatedCallback.expectations, expectation)
	return expectation
}

// Then sets up FederatedLoginUseCase.ExecuteFederatedCallback return parameters for the expectation previously defined by the When method
func (e *FederatedLoginUseCaseMockExecuteFederatedCallbackExpectation) Then(fp1 *mm_port.FederatedCallbackResponse, err error) *FederatedLoginUseCaseMock {
	e.results = &FederatedLoginUseCaseMockExecuteFederatedCallbackResults{fp1, err}
	return e.mock
}

// Times sets number of times FederatedLoginUseCase.ExecuteFederatedCallback should be invoked
func (mmExecuteFederatedCallback *mFederatedLoginUseCaseMockExecuteFederatedCallback) Times(n uint64) *mFederatedLoginUseCaseMockExecuteFederatedCallback {
	if n == 0 {
		mmExecuteFederatedCallback.mock.t.Fatalf("Times of FederatedLoginUseCaseMock.ExecuteFederatedCallback mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmExecuteFederatedCallback.expectedInvocations, n)
	mmExecuteFederatedCallback.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmExecuteFederatedCallback
}

func (mmExecuteFederatedCallback *mFederatedLoginUseCaseMockExecuteFederatedCallback) invocationsDone() bool {
	if len(mmExecuteFederatedCallback.expectations) == 0 && mmExecuteFederatedCallback.defaultExpectation == nil && mmExecuteFederatedCallback.mock.funcExecuteFederatedCallback == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmExecuteFederatedCallback.mock.afterExecuteFederatedCallbackCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmExecuteFederatedCallback.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// ExecuteFederatedCallback implements mm_port.FederatedLoginUseCase
func (mmExecuteFederatedCallback *FederatedLoginUseCaseMock) ExecuteFederatedCallback(ctx context.Context, cmd mm_port.FederatedCallbackCommand) (fp1 *mm_port.FederatedCallbackResponse, err error) {
	mm_atomic.AddUint64(&mmExecuteFederatedCallback.beforeExecuteFederatedCallbackCounter, 1)
	defer mm_atomic.AddUint64(&mmExecuteFederatedCallback.afterExecuteFederatedCallbackCounter, 1)

	mmExecuteFederatedCallback.t.Helper()

	if mmExecuteFederatedCallback.inspectFuncExecuteFederatedCallback != nil {
		mmExecuteFederatedCallback.inspectFuncExecuteFederatedCallback(ctx, cmd)
	}

	mm_params := FederatedLoginUseCaseMockExecuteFederatedCallbackParams{ctx, cmd}

	// Record call args
	mmExecuteFederatedCallback.ExecuteFederatedCallbackMock.mutex.Lock()
	mmExecuteFederatedCallback.ExecuteFederatedCallbackMock.callArgs = append(mmExecuteFederatedCallback.ExecuteFederatedCallbackMock.callArgs, &mm_params)
	mmExecuteFederatedCallback.ExecuteFederatedCallbackMock.mutex.Unlock()

	for _, e := range mmExecuteFederatedCallback.ExecuteFederatedCallbackMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.fp1, e.results.err
		}
	}

	if mmExecuteFederatedCallback.ExecuteFederatedCallbackMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmExecuteFederatedCallback.ExecuteFederatedCallbackMock.defaultExpectation.Counter, 1)
		mm_want := mmExecuteFederatedCallback.ExecuteFederatedCallbackMock.defaultExpectation.params
		mm_want_ptrs := mmExecuteFederatedCallback.ExecuteFederatedCallbackMock.defaultExpectation.paramPtrs

		mm_got := FederatedLoginUseCaseMockExecuteFederatedCallbackParams{ctx, cmd}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmExecuteFederatedCallback.t.Errorf("FederatedLoginUseCaseMock.ExecuteFederatedCallback got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmExecuteFederatedCallback.ExecuteFederatedCallbackMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.cmd != nil && !minimock.Equal(*mm_want_ptrs.cmd, mm_got.cmd) {
				mmExecuteFederatedCallback.t.Errorf("FederatedLoginUseCaseMock.ExecuteFederatedCallback got unexpected parameter cmd, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmExecuteFederatedCallback.ExecuteFederatedCallbackMock.defaultExpectation.expectationOrigins.originCmd, *mm_want_ptrs.cmd, mm_got.cmd, minimock.Diff(*mm_want_ptrs.cmd, mm_got.cmd))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmExecuteFederatedCallback.t.Errorf("FederatedLoginUseCaseMock.ExecuteFederatedCallback got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmExecuteFederatedCallback.ExecuteFederatedCallbackMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmExecuteFederatedCallback.ExecuteFederatedCallbackMock.defaultExpectation.results
		if mm_results == nil {
			mmExecuteFederatedCallback.t.Fatal("No results are set for the FederatedLoginUseCaseMock.ExecuteFederatedCallback")
		}
		return (*mm_results).fp1, (*mm_results).err
	}
	if mmExecuteFederatedCallback.funcExecuteFederatedCallback != nil {
		return mmExecuteFederatedCallback.funcExecuteFederatedCallback(ctx, cmd)
	}
	mmExecuteFederatedCallback.t.Fatalf("Unexpected call to FederatedLoginUseCaseMock.ExecuteFederatedCallback. %v %v", ctx, cmd)
	return
}

// ExecuteFederatedCallbackAfterCounter returns a count of finished FederatedLoginUseCaseMock.ExecuteFederatedCallback invocations
func (mmExecuteFederatedCallback *FederatedLoginUseCaseMock) ExecuteFederatedCallbackAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmExecuteFederatedCallback.afterExecuteFederatedCallbackCounter)
}

// ExecuteFederatedCallbackBeforeCounter returns a count of FederatedLoginUseCaseMock.ExecuteFederatedCallback invocations
func (mmExecuteFederatedCallback *FederatedLoginUseCaseMock) ExecuteFederatedCallbackBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmExecuteFederatedCallback.beforeExecuteFederatedCallbackCounter)
}

// Calls returns a list of arguments used in each call to FederatedLoginUseCaseMock.ExecuteFederatedCallback.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmExecuteFederatedCallback *mFederatedLoginUseCaseMockExecuteFederatedCallback) Calls() []*FederatedLoginUseCaseMockExecuteFederatedCallbackParams {
	mmExecuteFederatedCallback.mutex.RLock()

	argCopy := make([]*FederatedLoginUseCaseMockExecuteFederatedCallbackParams, len(mmExecuteFederatedCallback.callArgs))
	copy(argCopy, mmExecuteFederatedCallback.callArgs)

	mmExecuteFederatedCallback.mutex.RUnlock()

	return argCopy
}

// MinimockExecuteFederatedCallbackDone returns true if the count of the ExecuteFederatedCallback invocations corresponds
// the number of defined expectations
func (m *FederatedLoginUseCaseMock) MinimockExecuteFederatedCallbackDone() bool {
	if m.ExecuteFederatedCallbackMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.ExecuteFederatedCallbackMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.ExecuteFederatedCallbackMock.invocationsDone()
}

// MinimockExecuteFederatedCallbackInspect logs each unmet expectation
func (m *FederatedLoginUseCaseMock) MinimockExecuteFederatedCallbackInspect() {
	for _, e := range m.ExecuteFederatedCallbackMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to FederatedLoginUseCaseMock.ExecuteFederatedCallback at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterExecuteFederatedCallbackCounter := mm_atomic.LoadUint64(&m.afterExecuteFederatedCallbackCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.ExecuteFederatedCallbackMock.defaultExpectation != nil && afterExecuteFederatedCallbackCounter < 1 {
		if m.ExecuteFederatedCallbackMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to FederatedLoginUseCaseMock.ExecuteFederatedCallback at\n%s", m.ExecuteFederatedCallbackMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to FederatedLoginUseCaseMock.ExecuteFederatedCallback at\n%s with params: %#v", m.ExecuteFederatedCallbackMock.defaultExpectation.expectationOrigins.origin, *m.ExecuteFederatedCallbackMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcExecuteFederatedCallback != nil && afterExecuteFederatedCallbackCounter < 1 {
		m.t.Errorf("Expected call to FederatedLoginUseCaseMock.ExecuteFederatedCallback at\n%s", m.funcExecuteFederatedCallbackOrigin)
	}

	if !m.ExecuteFederatedCallbackMock.invocationsDone() && afterExecuteFederatedCallbackCounter > 0 {
		m.t.Errorf("Expected %d calls to FederatedLoginUseCaseMock.ExecuteFederatedCallback at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.ExecuteFederatedCallbackMock.expectedInvocations), m.ExecuteFederatedCallbackMock.expectedInvocationsOrigin, afterExecuteFederatedCallbackCounter)
	}
}

type mFederatedLoginUseCaseMockInitiateFederatedLogin struct {
	optional           bool
	mock               *FederatedLoginUseCaseMock
	defaultExpectation *FederatedLoginUseCaseMockInitiateFederatedLoginExpectation
	expectations       []*FederatedLoginUseCaseMockInitiateFederatedLoginExpectation

	callArgs []*FederatedLoginUseCaseMockInitiateFederatedLoginParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// FederatedLoginUseCaseMockInitiateFederatedLoginExpectation specifies expectation struct of the FederatedLoginUseCase.InitiateFederatedLogin
type FederatedLoginUseCaseMockInitiateFederatedLoginExpectation struct {
	mock               *FederatedLoginUseCaseMock
	params             *FederatedLoginUseCaseMockInitiateFederatedLoginParams
	paramPtrs          *FederatedLoginUseCaseMockInitiateFederatedLoginParamPtrs
	expectationOrigins FederatedLoginUseCaseMockInitiateFederatedLoginExpectationOrigins
	results            *FederatedLoginUseCaseMockInitiateFederatedLoginResults
	returnOrigin       string
	Counter            uint64
}

// FederatedLoginUseCaseMockInitiateFederatedLoginParams contains parameters of the FederatedLoginUseCase.InitiateFederatedLogin
type FederatedLoginUseCaseMockInitiateFederatedLoginParams struct {
	ctx context.Context
	cmd mm_port.InitiateFederatedLoginCommand
}

// FederatedLoginUseCaseMockInitiateFederatedLoginParamPtrs contains pointers to parameters of the FederatedLoginUseCase.InitiateFederatedLogin
type FederatedLoginUseCaseMockInitiateFederatedLoginParamPtrs struct {
	ctx *context.Context
	cmd *mm_port.InitiateFederatedLoginCommand
}

// FederatedLoginUseCaseMockInitiateFederatedLoginResults contains results of the FederatedLoginUseCase.InitiateFederatedLogin
type FederatedLoginUseCaseMockInitiateFederatedLoginResults struct {
	ip1 *mm_port.InitiateFederatedLoginResponse
	err error
}

// FederatedLoginUseCaseMockInitiateFederatedLoginOrigins contains origins of expectations of the FederatedLoginUseCase.InitiateFederatedLogin
type FederatedLoginUseCaseMockInitiateFederatedLoginExpectationOrigins struct {
	origin    string
	originCtx string
	originCmd string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmInitiateFederatedLogin *mFederatedLoginUseCaseMockInitiateFederatedLogin) Optional() *mFederatedLoginUseCaseMockInitiateFederatedLogin {
	mmInitiateFederatedLogin.optional = true
	return mmInitiateFederatedLogin
}

// Expect sets up expected params for FederatedLoginUseCase.InitiateFederatedLogin
func (mmInitiateFederatedLogin *mFederatedLoginUseCaseMockInitiateFederatedLogin) Expect(ctx context.Context, cmd mm_port.InitiateFederatedLoginCommand) *mFederatedLoginUseCaseMockInitiateFederatedLogin {
	if mmInitiateFederatedLogin.mock.funcInitiateFederatedLogin != nil {
		mmInitiateFederatedLogin.mock.t.Fatalf("FederatedLoginUseCaseMock.InitiateFederatedLogin mock is already set by Set")
	}

	if mmInitiateFederatedLogin.defaultExpectation == nil {
		mmInitiateFederatedLogin.defaultExpectation = &FederatedLoginUseCaseMockInitiateFederatedLoginExpectation{}
	}

	if mmInitiateFederatedLogin.defaultExpectation.paramPtrs != nil {
		mmInitiateFederatedLogin.mock.t.Fatalf("FederatedLoginUseCaseMock.InitiateFederatedLogin mock is already set by ExpectParams functions")
	}

	mmInitiateFederatedLogin.defaultExpectation.params = &FederatedLoginUseCaseMockInitiateFederatedLoginParams{ctx, cmd}
	mmInitiateFederatedLogin.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmInitiateFederatedLogin.expectations {
		if minimock.Equal(e.params, mmInitiateFederatedLogin.defaultExpectation.params) {
			mmInitiateFederatedLogin.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmInitiateFederatedLogin.defaultExpectation.params)
		}
	}

	return mmInitiateFederatedLogin
}

// ExpectCtxParam1 sets up expected param ctx for FederatedLoginUseCase.InitiateFederatedLogin
func (mmInitiateFederatedLogin *mFederatedLoginUseCaseMockInitiateFederatedLogin) ExpectCtxParam1(ctx context.Context) *mFederatedLoginUseCaseMockInitiateFederatedLogin {
	if mmInitiateFederatedLogin.mock.funcInitiateFederatedLogin != nil {
		mmInitiateFederatedLogin.mock.t.Fatalf("FederatedLoginUseCaseMock.InitiateFederatedLogin mock is already set by Set")
	}

	if mmInitiateFederatedLogin.defaultExpectation == nil {
		mmInitiateFederatedLogin.defaultExpectation = &FederatedLoginUseCaseMockInitiateFederatedLoginExpectation{}
	}

	if mmInitiateFederatedLogin.defaultExpectation.params != nil {
		mmInitiateFederatedLogin.mock.t.Fatalf("FederatedLoginUseCaseMock.InitiateFederatedLogin mock is already set by Expect")
	}

	if mmInitiateFederatedLogin.defaultExpectation.paramPtrs == nil {
		mmInitiateFederatedLogin.defaultExpectation.paramPtrs = &FederatedLoginUseCaseMockInitiateFederatedLoginParamPtrs{}
	}
	mmInitiateFederatedLogin.defaultExpectation.paramPtrs.ctx = &ctx
	mmInitiateFederatedLogin.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmInitiateFederatedLogin
}

// ExpectCmdParam2 sets up expected param cmd for FederatedLoginUseCase.InitiateFederatedLogin
func (mmInitiateFederatedLogin *mFederatedLoginUseCaseMockInitiateFederatedLogin) ExpectCmdParam2(cmd mm_port.InitiateFederatedLoginCommand) *mFederatedLoginUseCaseMockInitiateFederatedLogin {
	if mmInitiateFederatedLogin.mock.funcInitiateFederatedLogin != nil {
		mmInitiateFederatedLogin.mock.t.Fatalf("FederatedLoginUseCaseMock.InitiateFederatedLogin mock is already set by Set")
	}

	if mmInitiateFederatedLogin.defaultExpectation == nil {
		mmInitiateFederatedLogin.defaultExpectation = &FederatedLoginUseCaseMockInitiateFederatedLoginExpectation{}
	}

	if mmInitiateFederatedLogin.defaultExpectation.params != nil {
		mmInitiateFederatedLogin.mock.t.Fatalf("FederatedLoginUseCaseMock.InitiateFederatedLogin mock is already set by Expect")
	}

	if mmInitiateFederatedLogin.defaultExpectation.paramPtrs == nil {
		mmInitiateFederatedLogin.defaultExpectation.paramPtrs = &FederatedLoginUseCaseMockInitiateFederatedLoginParamPtrs{}
	}
	mmInitiateFederatedLogin.defaultExpectation.paramPtrs.cmd = &cmd
	mmInitiateFederatedLogin.defaultExpectation.expectationOrigins.originCmd = minimock.CallerInfo(1)

	return mmInitiateFederatedLogin
}

// Inspect accepts an inspector function that has same arguments as the FederatedLoginUseCase.InitiateFederatedLogin
func (mmInitiateFederatedLogin *mFederatedLoginUseCaseMockInitiateFederatedLogin) Inspect(f func(ctx context.Context, cmd mm_port.InitiateFederatedLoginCommand)) *mFederatedLoginUseCaseMockInitiateFederatedLogin {
	if mmInitiateFederatedLogin.mock.inspectFuncInitiateFederatedLogin != nil {
		mmInitiateFederatedLogin.mock.t.Fatalf("Inspect function is already set for FederatedLoginUseCaseMock.InitiateFederatedLogin")
	}

	mmInitiateFederatedLogin.mock.inspectFuncInitiateFederatedLogin = f

	return mmInitiateFederatedLogin
}

// Return sets up results that will be returned by FederatedLoginUseCase.InitiateFederatedLogin
func (mmInitiateFederatedLogin *mFederatedLoginUseCaseMockInitiateFederatedLogin) Return(ip1 *mm_port.InitiateFederatedLoginResponse, err error) *FederatedLoginUseCaseMock {
	if mmInitiateFederatedLogin.mock.funcInitiateFederatedLogin != nil {
		mmInitiateFederatedLogin.mock.t.Fatalf("FederatedLoginUseCaseMock.InitiateFederatedLogin mock is already set by Set")
	}

	if mmInitiateFederatedLogin.defaultExpectation == nil {
		mmInitiateFederatedLogin.defaultExpectation = &FederatedLoginUseCaseMockInitiateFederatedLoginExpectation{mock: mmInitiateFederatedLogin.mock}
	}
	mmInitiateFederatedLogin.defaultExpectation.results = &FederatedLoginUseCaseMockInitiateFederatedLoginResults{ip1, err}
	mmInitiateFederatedLogin.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmInitiateFederatedLogin.mock
}

// Set uses given function f to mock the FederatedLoginUseCase.InitiateFederatedLogin method
func (mmInitiateFederatedLogin *mFederatedLoginUseCaseMockInitiateFederatedLogin) Set(f func(ctx context.Context, cmd mm_port.InitiateFederatedLoginCommand) (ip1 *mm_port.InitiateFederatedLoginResponse, err error)) *FederatedLoginUseCaseMock {
	if mmInitiateFederatedLogin.defaultExpectation != nil {
		mmInitiateFederatedLogin.mock.t.Fatalf("Default expectation is already set for the FederatedLoginUseCase.InitiateFederatedLogin method")
	}

	if len(mmInitiateFederatedLogin.expectations) > 0 {
		mmInitiateFederatedLogin.mock.t.Fatalf("Some expectations are already set for the FederatedLoginUseCase.InitiateFederatedLogin method")
	}

	mmInitiateFederatedLogin.mock.funcInitiateFederatedLogin = f
	mmInitiateFederatedLogin.mock.funcInitiateFederatedLoginOrigin = minimock.CallerInfo(1)
	return mmInitiateFederatedLogin.mock
}

// When sets expectation for the FederatedLoginUseCase.InitiateFederatedLogin which will trigger the result defined by the following
// Then helper
func (mmInitiateFederatedLogin *mFederatedLoginUseCaseMockInitiateFederatedLogin) When(ctx context.Context, cmd mm_port.InitiateFederatedLoginCommand) *FederatedLoginUseCaseMockInitiateFederatedLoginExpectation {
	if mmInitiateFederatedLogin.mock.funcInitiateFederatedLogin != nil {
		mmInitiateFederatedLogin.mock.t.Fatalf("FederatedLoginUseCaseMock.InitiateFederatedLogin mock is already set by Set")
	}

	expectation := &FederatedLoginUseCaseMockInitiateFederatedLoginExpectation{
		mock:               mmInitiateFederatedLogin.mock,
		params:             &FederatedLoginUseCaseMockInitiateFederatedLoginParams{ctx, cmd},
		expectationOrigins: FederatedLoginUseCaseMockInitiateFederatedLoginExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmInitiateFederatedLogin.expectations = append(mmInitiateFederatedLogin.expectations, expectation)
	return expectation
}

// Then sets up FederatedLoginUseCase.InitiateFederatedLogin return parameters for the expectation previously defined by the When method
func (e *FederatedLoginUseCaseMockInitiateFederatedLoginExpectation) Then(ip1 *mm_port.InitiateFederatedLoginResponse, err error) *FederatedLoginUseCaseMock {
	e.results = &FederatedLoginUseCaseMockInitiateFederatedLoginResults{ip1, err}
	return e.mock
}

// Times sets number of times FederatedLoginUseCase.InitiateFederatedLogin should be invoked
func (mmInitiateFederatedLogin *mFederatedLoginUseCaseMockInitiateFederatedLogin) Times(n uint64) *mFederatedLoginUseCaseMockInitiateFederatedLogin {
	if n == 0 {
		mmInitiateFederatedLogin.mock.t.Fatalf("Times of FederatedLoginUseCaseMock.InitiateFederatedLogin mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmInitiateFederatedLogin.expectedInvocations, n)
	mmInitiateFederatedLogin.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmInitiateFederatedLogin
}

func (mmInitiateFederatedLogin *mFederatedLoginUseCaseMockInitiateFederatedLogin) invocationsDone() bool {
	if len(mmInitiateFederatedLogin.expectations) == 0 && mmInitiateFederatedLogin.defaultExpectation == nil && mmInitiateFederatedLogin.mock.funcInitiateFederatedLogin == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmInitiateFederatedLogin.mock.afterInitiateFederatedLoginCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmInitiateFederatedLogin.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// InitiateFederatedLogin implements mm_port.FederatedLoginUseCase
func (mmInitiateFederatedLogin *FederatedLoginUseCaseMock) InitiateFederatedLogin(ctx context.Context, cmd mm_port.InitiateFederatedLoginCommand) (ip1 *mm_port.InitiateFederatedLoginResponse, err error) {
	mm_atomic.AddUint64(&mmInitiateFederatedLogin.beforeInitiateFederatedLoginCounter, 1)
	defer mm_atomic.AddUint64(&mmInitiateFederatedLogin.afterInitiateFederatedLoginCounter, 1)

	mmInitiateFederatedLogin.t.Helper()

	if mmInitiateFederatedLogin.inspectFuncInitiateFederatedLogin != nil {
		mmInitiateFederatedLogin.inspectFuncInitiateFederatedLogin(ctx, cmd)
	}

	mm_params := FederatedLoginUseCaseMockInitiateFederatedLoginParams{ctx, cmd}

	// Record call args
	mmInitiateFederatedLogin.InitiateFederatedLoginMock.mutex.Lock()
	mmInitiateFederatedLogin.InitiateFederatedLoginMock.callArgs = append(mmInitiateFederatedLogin.InitiateFederatedLoginMock.callArgs, &mm_params)
	mmInitiateFederatedLogin.InitiateFederatedLoginMock.mutex.Unlock()

	for _, e := range mmInitiateFederatedLogin.InitiateFederatedLoginMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.ip1, e.results.err
		}
	}

	if mmInitiateFederatedLogin.InitiateFederatedLoginMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmInitiateFederatedLogin.InitiateFederatedLoginMock.defaultExpectation.Counter, 1)
		mm_want := mmInitiateFederatedLogin.InitiateFederatedLoginMock.defaultExpectation.params
		mm_want_ptrs := mmInitiateFederatedLogin.InitiateFederatedLoginMock.defaultExpectation.paramPtrs

		mm_got := FederatedLoginUseCaseMockInitiateFederatedLoginParams{ctx, cmd}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmInitiateFederatedLogin.t.Errorf("FederatedLoginUseCaseMock.InitiateFederatedLogin got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmInitiateFederatedLogin.InitiateFederatedLoginMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.cmd != nil && !minimock.Equal(*mm_want_ptrs.cmd, mm_got.cmd) {
				mmInitiateFederatedLogin.t.Errorf("FederatedLoginUseCaseMock.InitiateFederatedLogin got unexpected parameter cmd, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmInitiateFederatedLogin.InitiateFederatedLoginMock.defaultExpectation.expectationOrigins.originCmd, *mm_want_ptrs.cmd, mm_got.cmd, minimock.Diff(*mm_want_ptrs.cmd, mm_got.cmd))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmInitiateFederatedLogin.t.Errorf("FederatedLoginUseCaseMock.InitiateFederatedLogin got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmInitiateFederatedLogin.InitiateFederatedLoginMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmInitiateFederatedLogin.InitiateFederatedLoginMock.defaultExpectation.results
		if mm_results == nil {
			mmInitiateFederatedLogin.t.Fatal("No results are set for the FederatedLoginUseCaseMock.InitiateFederatedLogin")
		}
		return (*mm_results).ip1, (*mm_results).err
	}
	if mmInitiateFederatedLogin.funcInitiateFederatedLogin != nil {
		return mmInitiateFederatedLogin.funcInitiateFederatedLogin(ctx, cmd)
	}
	mmInitiateFederatedLogin.t.Fatalf("Unexpected call to FederatedLoginUseCaseMock.InitiateFederatedLogin. %v %v", ctx, cmd)
	return
}

// InitiateFederatedLoginAfterCounter returns a count of finished FederatedLoginUseCaseMock.InitiateFederatedLogin invocations
func (mmInitiateFederatedLogin *FederatedLoginUseCaseMock) InitiateFederatedLoginAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmInitiateFederatedLogin.afterInitiateFederatedLoginCounter)
}

// InitiateFederatedLoginBeforeCounter returns a count of FederatedLoginUseCaseMock.InitiateFederatedLogin invocations
func (mmInitiateFederatedLogin *FederatedLoginUseCaseMock) InitiateFederatedLoginBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmInitiateFederatedLogin.beforeInitiateFederatedLoginCounter)
}

// Calls returns a list of arguments used in each call to FederatedLoginUseCaseMock.InitiateFederatedLogin.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmInitiateFederatedLogin *mFederatedLoginUseCaseMockInitiateFederatedLogin) Calls() []*FederatedLoginUseCaseMockInitiateFederatedLoginParams {
	mmInitiateFederatedLogin.mutex.RLock()

	argCopy := make([]*FederatedLoginUseCaseMockInitiateFederatedLoginParams, len(mmInitiateFederatedLogin.callArgs))
	copy(argCopy, mmInitiateFederatedLogin.callArgs)

	mmInitiateFederatedLogin.mutex.RUnlock()

	return argCopy
}

// MinimockInitiateFederatedLoginDone returns true if the count of the InitiateFederatedLogin invocations corresponds
// the number of defined expectations
func (m *FederatedLoginUseCaseMock) MinimockInitiateFederatedLoginDone() bool {
	if m.InitiateFederatedLoginMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.InitiateFederatedLoginMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.InitiateFederatedLoginMock.invocationsDone()
}

// MinimockInitiateFederatedLoginInspect logs each unmet expectation
func (m *FederatedLoginUseCaseMock) MinimockInitiateFederatedLoginInspect() {
	for _, e := range m.InitiateFederatedLoginMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to FederatedLoginUseCaseMock.InitiateFederatedLogin at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterInitiateFederatedLoginCounter := mm_atomic.LoadUint64(&m.afterInitiateFederatedLoginCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.InitiateFederatedLoginMock.defaultExpectation != nil && afterInitiateFederatedLoginCounter < 1 {
		if m.InitiateFederatedLoginMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to FederatedLoginUseCaseMock.InitiateFederatedLogin at\n%s", m.InitiateFederatedLoginMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to FederatedLoginUseCaseMock.InitiateFederatedLogin at\n%s with params: %#v", m.InitiateFederatedLoginMock.defaultExpectation.expectationOrigins.origin, *m.InitiateFederatedLoginMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcInitiateFederatedLogin != nil && afterInitiateFederatedLoginCounter < 1 {
		m.t.Errorf("Expected call to FederatedLoginUseCaseMock.InitiateFederatedLogin at\n%s", m.funcInitiateFederatedLoginOrigin)
	}

	if !m.InitiateFederatedLoginMock.invocationsDone() && afterInitiateFederatedLoginCounter > 0 {
		m.t.Errorf("Expected %d calls to FederatedLoginUseCaseMock.InitiateFederatedLogin at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.InitiateFederatedLoginMock.expectedInvocations), m.InitiateFederatedLoginMock.expectedInvocationsOrigin, afterInitiateFederatedLoginCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *FederatedLoginUseCaseMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockExecuteFederatedCallbackInspect()

			m.MinimockInitiateFederatedLoginInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *FederatedLoginUseCaseMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *FederatedLoginUseCaseMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockExecuteFederatedCallbackDone() &&
		m.MinimockInitiateFederatedLoginDone()
}
