// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package portmock

//go:generate minimock -i sprezz-identity/internal/domain/port.LocalAuthUseCase -o local_auth_usecase_mock.go -n LocalAuthUseCaseMock -p portmock

import (
	"context"
	"sprezz-identity/internal/domain/model"
	mm_port "sprezz-identity/internal/domain/port"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
	"github.com/google/uuid"
)

// LocalAuthUseCaseMock implements mm_port.LocalAuthUseCase
type LocalAuthUseCaseMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcAuthenticateLocalCredentials          func(ctx context.Context, cmd mm_port.LocalLoginCommand) (lp1 *mm_port.LocalLoginResponse, err error)
	funcAuthenticateLocalCredentialsOrigin    string
	inspectFuncAuthenticateLocalCredentials   func(ctx context.Context, cmd mm_port.LocalLoginCommand)
	afterAuthenticateLocalCredentialsCounter  uint64
	beforeAuthenticateLocalCredentialsCounter uint64
	AuthenticateLocalCredentialsMock          mLocalAuthUseCaseMockAuthenticateLocalCredentials

	funcGetInteractionSession          func(ctx context.Context, tenantID uuid.UUID, interactionID string) (ip1 *model.InteractionSession, err error)
	funcGetInteractionSessionOrigin    string
	inspectFuncGetInteractionSession   func(ctx context.Context, tenantID uuid.UUID, interactionID string)
	afterGetInteractionSessionCounter  uint64
	beforeGetInteractionSessionCounter uint64
	GetInteractionSessionMock          mLocalAuthUseCaseMockGetInteractionSession

	funcGetLoginContext          func(ctx context.Context, cmd mm_port.GetLoginContextCommand) (lp1 *mm_port.LoginContextResponse, err error)
	funcGetLoginContextOrigin    string
	inspectFuncGetLoginContext   func(ctx context.Context, cmd mm_port.GetLoginContextCommand)
	afterGetLoginContextCounter  uint64
	beforeGetLoginContextCounter uint64
	GetLoginContextMock          mLocalAuthUseCaseMockGetLoginContext
}

// NewLocalAuthUseCaseMock returns a mock for mm_port.LocalAuthUseCase
func NewLocalAuthUseCaseMock(t minimock.Tester) *LocalAuthUseCaseMock {
	m := &LocalAuthUseCaseMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.AuthenticateLocalCredentialsMock = mLocalAuthUseCaseMockAuthenticateLocalCredentials{mock: m}
	m.AuthenticateLocalCredentialsMock.callArgs = []*LocalAuthUseCaseMockAuthenticateLocalCredentialsParams{}

	m.GetInteractionSessionMock = mLocalAuthUseCaseMockGetInteractionSession{mock: m}
	m.GetInteractionSessionMock.callArgs = []*LocalAuthUseCaseMockGetInteractionSessionParams{}

	m.GetLoginContextMock = mLocalAuthUseCaseMockGetLoginContext{mock: m}
	m.GetLoginContextMock.callArgs = []*LocalAuthUseCaseMockGetLoginContextParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mLocalAuthUseCaseMockAuthenticateLocalCredentials struct {
	optional           bool
	mock               *LocalAuthUseCaseMock
	defaultExpectation *LocalAuthUseCaseMockAuthenticateLocalCredentialsExpectation
	expectations       []*LocalAuthUseCaseMockAuthenticateLocalCredentialsExpectation

	callArgs []*LocalAuthUseCaseMockAuthenticateLocalCredentialsParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// LocalAuthUseCaseMockAuthenticateLocalCredentialsExpectation specifies expectation struct of the LocalAuthUseCase.AuthenticateLocalCredentials
type LocalAuthUseCaseMockAuthenticateLocalCredentialsExpectation struct {
	mock               *LocalAuthUseCaseMock
	params             *LocalAuthUseCaseMockAuthenticateLocalCredentialsParams
	paramPtrs          *LocalAuthUseCaseMockAuthenticateLocalCredentialsParamPtrs
	expectationOrigins LocalAuthUseCaseMockAuthenticateLocalCredentialsExpectationOrigins
	results            *LocalAuthUseCaseMockAuthenticateLocalCredentialsResults
	returnOrigin       string
	Counter            uint64
}

// LocalAuthUseCaseMockAuthenticateLocalCredentialsParams contains parameters of the LocalAuthUseCase.AuthenticateLocalCredentials
type LocalAuthUseCaseMockAuthenticateLocalCredentialsParams struct {
	ctx context.Context
	cmd mm_port.LocalLoginCommand
}

// LocalAuthUseCaseMockAuthenticateLocalCredentialsParamPtrs contains pointers to parameters of the LocalAuthUseCase.AuthenticateLocalCredentials
type LocalAuthUseCaseMockAuthenticateLocalCredentialsParamPtrs struct {
	ctx *context.Context
	cmd *mm_port.LocalLoginCommand
}

// LocalAuthUseCaseMockAuthenticateLocalCredentialsResults contains results of the LocalAuthUseCase.AuthenticateLocalCredentials
type LocalAuthUseCaseMockAuthenticateLocalCredentialsResults struct {
	lp1 *mm_port.LocalLoginResponse
	err error
}

// LocalAuthUseCaseMockAuthenticateLocalCredentialsOrigins contains origins of expectations of the LocalAuthUseCase.AuthenticateLocalCredentials
type LocalAuthUseCaseMockAuthenticateLocalCredentialsExpectationOrigins struct {
	origin    string
	originCtx string
	originCmd string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmAuthenticateLocalCredentials *mLocalAuthUseCaseMockAuthenticateLocalCredentials) Optional() *mLocalAuthUseCaseMockAuthenticateLocalCredentials {
	mmAuthenticateLocalCredentials.optional = true
	return mmAuthenticateLocalCredentials
}

// Expect sets up expected params for LocalAuthUseCase.AuthenticateLocalCredentials
func (mmAuthenticateLocalCredentials *mLocalAuthUseCaseMockAuthenticateLocalCredentials) Expect(ctx context.Context, cmd mm_port.LocalLoginCommand) *mLocalAuthUseCaseMockAuthenticateLocalCredentials {
	if mmAuthenticateLocalCredentials.mock.funcAuthenticateLocalCredentials != nil {
		mmAuthenticateLocalCredentials.mock.t.Fatalf("LocalAuthUseCaseMock.AuthenticateLocalCredentials mock is already set by Set")
	}

	if mmAuthenticateLocalCredentials.defaultExpectation == nil {
		mmAuthenticateLocalCredentials.defaultExpectation = &LocalAuthUseCaseMockAuthenticateLocalCredentialsExpectation{}
	}

	if mmAuthenticateLocalCredentials.defaultExpectation.paramPtrs != nil {
		mmAuthenticateLocalCredentials.mock.t.Fatalf("LocalAuthUseCaseMock.AuthenticateLocalCredentials mock is already set by ExpectParams functions")
	}

	mmAuthenticateLocalCredentials.defaultExpectation.params = &LocalAuthUseCaseMockAuthenticateLocalCredentialsParams{ctx, cmd}
	mmAuthenticateLocalCredentials.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmAuthenticateLocalCredentials.expectations {
		if minimock.Equal(e.params, mmAuthenticateLocalCredentials.defaultExpectation.params) {
			mmAuthenticateLocalCredentials.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmAuthenticateLocalCredentials.defaultExpectation.params)
		}
	}

	return mmAuthenticateLocalCredentials
}

// ExpectCtxParam1 sets up expected param ctx for LocalAuthUseCase.AuthenticateLocalCredentials
func (mmAuthenticateLocalCredentials *mLocalAuthUseCaseMockAuthenticateLocalCredentials) ExpectCtxParam1(ctx context.Context) *mLocalAuthUseCaseMockAuthenticateLocalCredentials {
	if mmAuthenticateLocalCredentials.mock.funcAuthenticateLocalCredentials != nil {
		mmAuthenticateLocalCredentials.mock.t.Fatalf("LocalAuthUseCaseMock.AuthenticateLocalCredentials mock is already set by Set")
	}

	if mmAuthenticateLocalCredentials.defaultExpectation == nil {
		mmAuthenticateLocalCredentials.defaultExpectation = &LocalAuthUseCaseMockAuthenticateLocalCredentialsExpectation{}
	}

	if mmAuthenticateLocalCredentials.defaultExpectation.params != nil {
		mmAuthenticateLocalCredentials.mock.t.Fatalf("LocalAuthUseCaseMock.AuthenticateLocalCredentials mock is already set by Expect")
	}

	if mmAuthenticateLocalCredentials.defaultExpectation.paramPtrs == nil {
		mmAuthenticateLocalCredentials.defaultExpectation.paramPtrs = &LocalAuthUseCaseMockAuthenticateLocalCredentialsParamPtrs{}
	}
	mmAuthenticateLocalCredentials.defaultExpectation.paramPtrs.ctx = &ctx
	mmAuthenticateLocalCredentials.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmAuthenticateLocalCredentials
}

// ExpectCmdParam2 sets up expected param cmd for LocalAuthUseCase.AuthenticateLocalCredentials
func (mmAuthenticateLocalCredentials *mLocalAuthUseCaseMockAuthenticateLocalCredentials) ExpectCmdParam2(cmd mm_port.LocalLoginCommand) *mLocalAuthUseCaseMockAuthenticateLocalCredentials {
	if mmAuthenticateLocalCredentials.mock.funcAuthenticateLocalCredentials != nil {
		mmAuthenticateLocalCredentials.mock.t.Fatalf("LocalAuthUseCaseMock.AuthenticateLocalCredentials mock is already set by Set")
	}

	if mmAuthenticateLocalCredentials.defaultExpectation == nil {
		mmAuthenticateLocalCredentials.defaultExpectation = &LocalAuthUseCaseMockAuthenticateLocalCredentialsExpectation{}
	}

	if mmAuthenticateLocalCredentials.defaultExpectation.params != nil {
		mmAuthenticateLocalCredentials.mock.t.Fatalf("LocalAuthUseCaseMock.AuthenticateLocalCredentials mock is already set by Expect")
	}

	if mmAuthenticateLocalCredentials.defaultExpectation.paramPtrs == nil {
		mmAuthenticateLocalCredentials.defaultExpectation.paramPtrs = &LocalAuthUseCaseMockAuthenticateLocalCredentialsParamPtrs{}
	}
	mmAuthenticateLocalCredentials.defaultExpectation.paramPtrs.cmd = &cmd
	mmAuthenticateLocalCredentials.defaultExpectation.expectationOrigins.originCmd = minimock.CallerInfo(1)

	return mmAuthenticateLocalCredentials
}

// Inspect accepts an inspector function that has same arguments as the LocalAuthUseCase.AuthenticateLocalCredentials
func (mmAuthenticateLocalCredentials *mLocalAuthUseCaseMockAuthenticateLocalCredentials) Inspect(f func(ctx context.Context, cmd mm_port.LocalLoginCommand)) *mLocalAuthUseCaseMockAuthenticateLocalCredentials {
	if mmAuthenticateLocalCredentials.mock.inspectFuncAuthenticateLocalCredentials != nil {
		mmAuthenticateLocalCredentials.mock.t.Fatalf("Inspect function is already set for LocalAuthUseCaseMock.AuthenticateLocalCredentials")
	}

	mmAuthenticateLocalCredentials.mock.inspectFuncAuthenticateLocalCredentials = f

	return mmAuthenticateLocalCredentials
}

// Return sets up results that will be returned by LocalAuthUseCase.AuthenticateLocalCredentials
func (mmAuthenticateLocalCredentials *mLocalAuthUseCaseMockAuthenticateLocalCredentials) Return(lp1 *mm_port.LocalLoginResponse, err error) *LocalAuthUseCaseMock {
	if mmAuthenticateLocalCredentials.mock.funcAuthenticateLocalCredentials != nil {
		mmAuthenticateLocalCredentials.mock.t.Fatalf("LocalAuthUseCaseMock.AuthenticateLocalCredentials mock is already set by Set")
	}

	if mmAuthenticateLocalCredentials.defaultExpectation == nil {
		mmAuthenticateLocalCredentials.defaultExpectation = &LocalAuthUseCaseMockAuthenticateLocalCredentialsExpectation{mock: mmAuthenticateLocalCredentials.mock}
	}
	mmAuthenticateLocalCredentials.defaultExpectation.results = &LocalAuthUseCaseMockAuthenticateLocalCredentialsResults{lp1, err}
	mmAuthenticateLocalCredentials.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmAuthenticateLocalCredentials.mock
}

// Set uses given function f to mock the LocalAuthUseCase.AuthenticateLocalCredentials method
func (mmAuthenticateLocalCredentials *mLocalAuthUseCaseMockAuthenticateLocalCredentials) Set(f func(ctx context.Context, cmd mm_port.LocalLoginCommand) (lp1 *mm_port.LocalLoginResponse, err error)) *LocalAuthUseCaseMock {
	if mmAuthenticateLocalCredentials.defaultExpectation != nil {
		mmAuthenticateLocalCredentials.mock.t.Fatalf("Default expectation is already set for the LocalAuthUseCase.AuthenticateLocalCredentials method")
	}

	if len(mmAuthenticateLocalCredentials.expectations) > 0 {
		mmAuthenticateLocalCredentials.mock.t.Fatalf("Some expectations are already set for the LocalAuthUseCase.AuthenticateLocalCredentials method")
	}

	mmAuthenticateLocalCredentials.mock.funcAuthenticateLocalCredentials = f
	mmAuthenticateLocalCredentials.mock.funcAuthenticateLocalCredentialsOrigin = minimock.CallerInfo(1)
	return mmAuthenticateLocalCredentials.mock
}

// When sets expectation for the LocalAuthUseCase.AuthenticateLocalCredentials which will trigger the result defined by the following
// Then helper
func (mmAuthenticateLocalCredentials *mLocalAuthUseCaseMockAuthenticateLocalCredentials) When(ctx context.Context, cmd mm_port.LocalLoginCommand) *LocalAuthUseCaseMockAuthenticateLocalCredentialsExpectation {
	if mmAuthenticateLocalCredentials.mock.funcAuthenticateLocalCredentials != nil {
		mmAuthenticateLocalCredentials.mock.t.Fatalf("LocalAuthUseCaseMock.AuthenticateLocalCredentials mock is already set by Set")
	}

	expectation := &LocalAuthUseCaseMockAuthenticateLocalCredentialsExpectation{
		mock:               mmAuthenticateLocalCredentials.mock,
		params:             &LocalAuthUseCaseMockAuthenticateLocalCredentialsParams{ctx, cmd},
		expectationOrigins: LocalAuthUseCaseMockAuthenticateLocalCredentialsExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmAuthenticateLocalCredentials.expectations = append(mmAuthenticateLocalCredentials.expectations, expectation)
	return expectation
}

// Then sets up LocalAuthUseCase.AuthenticateLocalCredentials return parameters for the expectation previously defined by the When method
func (e *LocalAuthUseCaseMockAuthenticateLocalCredentialsExpectation) Then(lp1 *mm_port.LocalLoginResponse, err error) *LocalAuthUseCaseMock {
	e.results = &LocalAuthUseCaseMockAuthenticateLocalCredentialsResults{lp1, err}
	return e.mock
}

// Times sets number of times LocalAuthUseCase.AuthenticateLocalCredentials should be invoked
func (mmAuthenticateLocalCredentials *mLocalAuthUseCaseMockAuthenticateLocalCredentials) Times(n uint64) *mLocalAuthUseCaseMockAuthenticateLocalCredentials {
	if n == 0 {
		mmAuthenticateLocalCredentials.mock.t.Fatalf("Times of LocalAuthUseCaseMock.AuthenticateLocalCredentials mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmAuthenticateLocalCredentials.expectedInvocations, n)
	mmAuthenticateLocalCredentials.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmAuthenticateLocalCredentials
}

func (mmAuthenticateLocalCredentials *mLocalAuthUseCaseMockAuthenticateLocalCredentials) invocationsDone() bool {
	if len(mmAuthenticateLocalCredentials.expectations) == 0 && mmAuthenticateLocalCredentials.defaultExpectation == nil && mmAuthenticateLocalCredentials.mock.funcAuthenticateLocalCredentials == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmAuthenticateLocalCredentials.mock.afterAuthenticateLocalCredentialsCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmAuthenticateLocalCredentials.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// AuthenticateLocalCredentials implements mm_port.LocalAuthUseCase
func (mmAuthenticateLocalCredentials *LocalAuthUseCaseMock) AuthenticateLocalCredentials(ctx context.Context, cmd mm_port.LocalLoginCommand) (lp1 *mm_port.LocalLoginResponse, err error) {
	mm_atomic.AddUint64(&mmAuthenticateLocalCredentials.beforeAuthenticateLocalCredentialsCounter, 1)
	defer mm_atomic.AddUint64(&mmAuthenticateLocalCredentials.afterAuthenticateLocalCredentialsCounter, 1)

	mmAuthenticateLocalCredentials.t.Helper()

	if mmAuthenticateLocalCredentials.inspectFuncAuthenticateLocalCredentials != nil {
		mmAuthenticateLocalCredentials.inspectFuncAuthenticateLocalCredentials(ctx, cmd)
	}

	mm_params := LocalAuthUseCaseMockAuthenticateLocalCredentialsParams{ctx, cmd}

	// Record call args
	mmAuthenticateLocalCredentials.AuthenticateLocalCredentialsMock.mutex.Lock()
	mmAuthenticateLocalCredentials.AuthenticateLocalCredentialsMock.callArgs = append(mmAuthenticateLocalCredentials.AuthenticateLocalCredentialsMock.callArgs, &mm_params)
	mmAuthenticateLocalCredentials.AuthenticateLocalCredentialsMock.mutex.Unlock()

	for _, e := range mmAuthenticateLocalCredentials.AuthenticateLocalCredentialsMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.lp1, e.results.err
		}
	}

	if mmAuthenticateLocalCredentials.AuthenticateLocalCredentialsMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmAuthenticateLocalCredentials.AuthenticateLocalCredentialsMock.defaultExpectation.Counter, 1)
		mm_want := mmAuthenticateLocalCredentials.AuthenticateLocalCredentialsMock.defaultExpectation.params
		mm_want_ptrs := mmAuthenticateLocalCredentials.AuthenticateLocalCredentialsMock.defaultExpectation.paramPtrs

		mm_got := LocalAuthUseCaseMockAuthenticateLocalCredentialsParams{ctx, cmd}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmAuthenticateLocalCredentials.t.Errorf("LocalAuthUseCaseMock.AuthenticateLocalCredentials got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmAuthenticateLocalCredentials.AuthenticateLocalCredentialsMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.cmd != nil && !minimock.Equal(*mm_want_ptrs.cmd, mm_got.cmd) {
				mmAuthenticateLocalCredentials.t.Errorf("LocalAuthUseCaseMock.AuthenticateLocalCredentials got unexpected parameter cmd, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmAuthenticateLocalCredentials.AuthenticateLocalCredentialsMock.defaultExpectation.expectationOrigins.originCmd, *mm_want_ptrs.cmd, mm_got.cmd, minimock.Diff(*mm_want_ptrs.cmd, mm_got.cmd))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmAuthenticateLocalCredentials.t.Errorf("LocalAuthUseCaseMock.AuthenticateLocalCredentials got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmAuthenticateLocalCredentials.AuthenticateLocalCredentialsMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmAuthenticateLocalCredentials.AuthenticateLocalCredentialsMock.defaultExpectation.results
		if mm_results == nil {
			mmAuthenticateLocalCredentials.t.Fatal("No results are set for the LocalAuthUseCaseMock.AuthenticateLocalCredentials")
		}
		return (*mm_results).lp1, (*mm_results).err
	}
	if mmAuthenticateLocalCredentials.funcAuthenticateLocalCredentials != nil {
		return mmAuthenticateLocalCredentials.funcAuthenticateLocalCredentials(ctx, cmd)
	}
	mmAuthenticateLocalCredentials.t.Fatalf("Unexpected call to LocalAuthUseCaseMock.AuthenticateLocalCredentials. %v %v", ctx, cmd)
	return
}

// AuthenticateLocalCredentialsAfterCounter returns a count of finished LocalAuthUseCaseMock.AuthenticateLocalCredentials invocations
func (mmAuthenticateLocalCredentials *LocalAuthUseCaseMock) AuthenticateLocalCredentialsAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmAuthenticateLocalCredentials.afterAuthenticateLocalCredentialsCounter)
}

// AuthenticateLocalCredentialsBeforeCounter returns a count of LocalAuthUseCaseMock.AuthenticateLocalCredentials invocations
func (mmAuthenticateLocalCredentials *LocalAuthUseCaseMock) AuthenticateLocalCredentialsBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmAuthenticateLocalCredentials.beforeAuthenticateLocalCredentialsCounter)
}

// Calls returns a list of arguments used in each call to LocalAuthUseCaseMock.AuthenticateLocalCredentials.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmAuthenticateLocalCredentials *mLocalAuthUseCaseMockAuthenticateLocalCredentials) Calls() []*LocalAuthUseCaseMockAuthenticateLocalCredentialsParams {
	mmAuthenticateLocalCredentials.mutex.RLock()

	argCopy := make([]*LocalAuthUseCaseMockAuthenticateLocalCredentialsParams, len(mmAuthenticateLocalCredentials.callArgs))
	copy(argCopy, mmAuthenticateLocalCredentials.callArgs)

	mmAuthenticateLocalCredentials.mutex.RUnlock()

	return argCopy
}

// MinimockAuthenticateLocalCredentialsDone returns true if the count of the AuthenticateLocalCredentials invocations corresponds
// the number of defined expectations
func (m *LocalAuthUseCaseMock) MinimockAuthenticateLocalCredentialsDone() bool {
	if m.AuthenticateLocalCredentialsMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.AuthenticateLocalCredentialsMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.AuthenticateLocalCredentialsMock.invocationsDone()
}

// MinimockAuthenticateLocalCredentialsInspect logs each unmet expectation
func (m *LocalAuthUseCaseMock) MinimockAuthenticateLocalCredentialsInspect() {
	for _, e := range m.AuthenticateLocalCredentialsMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to LocalAuthUseCaseMock.AuthenticateLocalCredentials at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterAuthenticateLocalCredentialsCounter := mm_atomic.LoadUint64(&m.afterAuthenticateLocalCredentialsCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.AuthenticateLocalCredentialsMock.defaultExpectation != nil && afterAuthenticateLocalCredentialsCounter < 1 {
		if m.AuthenticateLocalCredentialsMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to LocalAuthUseCaseMock.AuthenticateLocalCredentials at\n%s", m.AuthenticateLocalCredentialsMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to LocalAuthUseCaseMock.AuthenticateLocalCredentials at\n%s with params: %#v", m.AuthenticateLocalCredentialsMock.defaultExpectation.expectationOrigins.origin, *m.AuthenticateLocalCredentialsMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcAuthenticateLocalCredentials != nil && afterAuthenticateLocalCredentialsCounter < 1 {
		m.t.Errorf("Expected call to LocalAuthUseCaseMock.AuthenticateLocalCredentials at\n%s", m.funcAuthenticateLocalCredentialsOrigin)
	}

	if !m.AuthenticateLocalCredentialsMock.invocationsDone() && afterAuthenticateLocalCredentialsCounter > 0 {
		m.t.Errorf("Expected %d calls to LocalAuthUseCaseMock.AuthenticateLocalCredentials at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.AuthenticateLocalCredentialsMock.expectedInvocations), m.AuthenticateLocalCredentialsMock.expectedInvocationsOrigin, afterAuthenticateLocalCredentialsCounter)
	}
}

type mLocalAuthUseCaseMockGetInteractionSession struct {
	optional           bool
	mock               *LocalAuthUseCaseMock
	defaultExpectation *LocalAuthUseCaseMockGetInteractionSessionExpectation
	expectations       []*LocalAuthUseCaseMockGetInteractionSessionExpectation

	callArgs []*LocalAuthUseCaseMockGetInteractionSessionParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// LocalAuthUseCaseMockGetInteractionSessionExpectation specifies expectation struct of the LocalAuthUseCase.GetInteractionSession
type LocalAuthUseCaseMockGetInteractionSessionExpectation struct {
	mock               *LocalAuthUseCaseMock
	params             *LocalAuthUseCaseMockGetInteractionSessionParams
	paramPtrs          *LocalAuthUseCaseMockGetInteractionSessionParamPtrs
	expectationOrigins LocalAuthUseCaseMockGetInteractionSessionExpectationOrigins
	results            *LocalAuthUseCaseMockGetInteractionSessionResults
	returnOrigin       string
	Counter            uint64
}

// LocalAuthUseCaseMockGetInteractionSessionParams contains parameters of the LocalAuthUseCase.GetInteractionSession
type LocalAuthUseCaseMockGetInteractionSessionParams struct {
	ctx           context.Context
	tenantID      uuid.UUID
	interactionID string
}

// LocalAuthUseCaseMockGetInteractionSessionParamPtrs contains pointers to parameters of the LocalAuthUseCase.GetInteractionSession
type LocalAuthUseCaseMockGetInteractionSessionParamPtrs struct {
	ctx           *context.Context
	tenantID      *uuid.UUID
	interactionID *string
}

// LocalAuthUseCaseMockGetInteractionSessionResults contains results of the LocalAuthUseCase.GetInteractionSession
type LocalAuthUseCaseMockGetInteractionSessionResults struct {
	ip1 *model.InteractionSession
	err error
}

// LocalAuthUseCaseMockGetInteractionSessionOrigins contains origins of expectations of the LocalAuthUseCase.GetInteractionSession
type LocalAuthUseCaseMockGetInteractionSessionExpectationOrigins struct {
	origin              string
	originCtx           string
	originTenantID      string
	originInteractionID string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmGetInteractionSession *mLocalAuthUseCaseMockGetInteractionSession) Optional() *mLocalAuthUseCaseMockGetInteractionSession {
	mmGetInteractionSession.optional = true
	return mmGetInteractionSession
}

// Expect sets up expected params for LocalAuthUseCase.GetInteractionSession
func (mmGetInteractionSession *mLocalAuthUseCaseMockGetInteractionSession) Expect(ctx context.Context, tenantID uuid.UUID, interactionID string) *mLocalAuthUseCaseMockGetInteractionSession {
	if mmGetInteractionSession.mock.funcGetInteractionSession != nil {
		mmGetInteractionSession.mock.t.Fatalf("LocalAuthUseCaseMock.GetInteractionSession mock is already set by Set")
	}

	if mmGetInteractionSession.defaultExpectation == nil {
		mmGetInteractionSession.defaultExpectation = &LocalAuthUseCaseMockGetInteractionSessionExpectation{}
	}

	if mmGetInteractionSession.defaultExpectation.paramPtrs != nil {
		mmGetInteractionSession.mock.t.Fatalf("LocalAuthUseCaseMock.GetInteractionSession mock is already set by ExpectParams functions")
	}

	mmGetInteractionSession.defaultExpectation.params = &LocalAuthUseCaseMockGetInteractionSessionParams{ctx, tenantID, interactionID}
	mmGetInteractionSession.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmGetInteractionSession.expectations {
		if minimock.Equal(e.params, mmGetInteractionSession.defaultExpectation.params) {
			mmGetInteractionSession.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGetInteractionSession.defaultExpectation.params)
		}
	}

	return mmGetInteractionSession
}

// ExpectCtxParam1 sets up expected param ctx for LocalAuthUseCase.GetInteractionSession
func (mmGetInteractionSession *mLocalAuthUseCaseMockGetInteractionSession) ExpectCtxParam1(ctx context.Context) *mLocalAuthUseCaseMockGetInteractionSession {
	if mmGetInteractionSession.mock.funcGetInteractionSession != nil {
		mmGetInteractionSession.mock.t.Fatalf("LocalAuthUseCaseMock.GetInteractionSession mock is already set by Set")
	}

	if mmGetInteractionSession.defaultExpectation == nil {
		mmGetInteractionSession.defaultExpectation = &LocalAuthUseCaseMockGetInteractionSessionExpectation{}
	}

	if mmGetInteractionSession.defaultExpectation.params != nil {
		mmGetInteractionSession.mock.t.Fatalf("LocalAuthUseCaseMock.GetInteractionSession mock is already set by Expect")
	}

	if mmGetInteractionSession.defaultExpectation.paramPtrs == nil {
		mmGetInteractionSession.defaultExpectation.paramPtrs = &LocalAuthUseCaseMockGetInteractionSessionParamPtrs{}
	}
	mmGetInteractionSession.defaultExpectation.paramPtrs.ctx = &ctx
	mmGetInteractionSession.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmGetInteractionSession
}

// ExpectTenantIDParam2 sets up expected param tenantID for LocalAuthUseCase.GetInteractionSession
func (mmGetInteractionSession *mLocalAuthUseCaseMockGetInteractionSession) ExpectTenantIDParam2(tenantID uuid.UUID) *mLocalAuthUseCaseMockGetInteractionSession {
	if mmGetInteractionSession.mock.funcGetInteractionSession != nil {
		mmGetInteractionSession.mock.t.Fatalf("LocalAuthUseCaseMock.GetInteractionSession mock is already set by Set")
	}

	if mmGetInteractionSession.defaultExpectation == nil {
		mmGetInteractionSession.defaultExpectation = &LocalAuthUseCaseMockGetInteractionSessionExpectation{}
	}

	if mmGetInteractionSession.defaultExpectation.params != nil {
		mmGetInteractionSession.mock.t.Fatalf("LocalAuthUseCaseMock.GetInteractionSession mock is already set by Expect")
	}

	if mmGetInteractionSession.defaultExpectation.paramPtrs == nil {
		mmGetInteractionSession.defaultExpectation.paramPtrs = &LocalAuthUseCaseMockGetInteractionSessionParamPtrs{}
	}
	mmGetInteractionSession.defaultExpectation.paramPtrs.tenantID = &tenantID
	mmGetInteractionSession.defaultExpectation.expectationOrigins.originTenantID = minimock.CallerInfo(1)

	return mmGetInteractionSession
}

// ExpectInteractionIDParam3 sets up expected param interactionID for LocalAuthUseCase.GetInteractionSession
func (mmGetInteractionSession *mLocalAuthUseCaseMockGetInteractionSession) ExpectInteractionIDParam3(interactionID string) *mLocalAuthUseCaseMockGetInteractionSession {
	if mmGetInteractionSession.mock.funcGetInteractionSession != nil {
		mmGetInteractionSession.mock.t.Fatalf("LocalAuthUseCaseMock.GetInteractionSession mock is already set by Set")
	}

	if mmGetInteractionSession.defaultExpectation == nil {
		mmGetInteractionSession.defaultExpectation = &LocalAuthUseCaseMockGetInteractionSessionExpectation{}
	}

	if mmGetInteractionSession.defaultExpectation.params != nil {
		mmGetInteractionSession.mock.t.Fatalf("LocalAuthUseCaseMock.GetInteractionSession mock is already set by Expect")
	}

	if mmGetInteractionSession.defaultExpectation.paramPtrs == nil {
		mmGetInteractionSession.defaultExpectation.paramPtrs = &LocalAuthUseCaseMockGetInteractionSessionParamPtrs{}
	}
	mmGetInteractionSession.defaultExpectation.paramPtrs.interactionID = &interactionID
	mmGetInteractionSession.defaultExpectation.expectationOrigins.originInteractionID = minimock.CallerInfo(1)

	return mmGetInteractionSession
}

// Inspect accepts an inspector function that has same arguments as the LocalAuthUseCase.GetInteractionSession
func (mmGetInteractionSession *mLocalAuthUseCaseMockGetInteractionSession) Inspect(f func(ctx context.Context, tenantID uuid.UUID, interactionID string)) *mLocalAuthUseCaseMockGetInteractionSession {
	if mmGetInteractionSession.mock.inspectFuncGetInteractionSession != nil {
		mmGetInteractionSession.mock.t.Fatalf("Inspect function is already set for LocalAuthUseCaseMock.GetInteractionSession")
	}

	mmGetInteractionSession.mock.inspectFuncGetInteractionSession = f

	return mmGetInteractionSession
}

// Return sets up results that will be returned by LocalAuthUseCase.GetInteractionSession
func (mmGetInteractionSession *mLocalAuthUseCaseMockGetInteractionSession) Return(ip1 *model.InteractionSession, err error) *LocalAuthUseCaseMock {
	if mmGetInteractionSession.mock.funcGetInteractionSession != nil {
		mmGetInteractionSession.mock.t.Fatalf("LocalAuthUseCaseMock.GetInteractionSession mock is already set by Set")
	}

	if mmGetInteractionSession.defaultExpectation == nil {
		mmGetInteractionSession.defaultExpectation = &LocalAuthUseCaseMockGetInteractionSessionExpectation{mock: mmGetInteractionSession.mock}
	}
	mmGetInteractionSession.defaultExpectation.results = &LocalAuthUseCaseMockGetInteractionSessionResults{ip1, err}
	mmGetInteractionSession.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmGetInteractionSession.mock
}

// Set uses given function f to mock the LocalAuthUseCase.GetInteractionSession method
func (mmGetInteractionSession *mLocalAuthUseCaseMockGetInteractionSession) Set(f func(ctx context.Context, tenantID uuid.UUID, interactionID string) (ip1 *model.InteractionSession, err error)) *LocalAuthUseCaseMock {
	if mmGetInteractionSession.defaultExpectation != nil {
		mmGetInteractionSession.mock.t.Fatalf("Default expectation is already set for the LocalAuthUseCase.GetInteractionSession method")
	}

	if len(mmGetInteractionSession.expectations) > 0 {
		mmGetInteractionSession.mock.t.Fatalf("Some expectations are already set for the LocalAuthUseCase.GetInteractionSession method")
	}

	mmGetInteractionSession.mock.funcGetInteractionSession = f
	mmGetInteractionSession.mock.funcGetInteractionSessionOrigin = minimock.CallerInfo(1)
	return mmGetInteractionSession.mock
}

// When sets expectation for the LocalAuthUseCase.GetInteractionSession which will trigger the result defined by the following
// Then helper
func (mmGetInteractionSession *mLocalAuthUseCaseMockGetInteractionSession) When(ctx context.Context, tenantID uuid.UUID, interactionID string) *LocalAuthUseCaseMockGetInteractionSessionExpectation {
	if mmGetInteractionSession.mock.funcGetInteractionSession != nil {
		mmGetInteractionSession.mock.t.Fatalf("LocalAuthUseCaseMock.GetInteractionSession mock is already set by Set")
	}

	expectation := &LocalAuthUseCaseMockGetInteractionSessionExpectation{
		mock:               mmGetInteractionSession.mock,
		params:             &LocalAuthUseCaseMockGetInteractionSessionParams{ctx, tenantID, interactionID},
		expectationOrigins: LocalAuthUseCaseMockGetInteractionSessionExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmGetInteractionSession.expectations = append(mmGetInteractionSession.expectations, expectation)
	return expectation
}

// Then sets up LocalAuthUseCase.GetInteractionSession return parameters for the expectation previously defined by the When method
func (e *LocalAuthUseCaseMockGetInteractionSessionExpectation) Then(ip1 *model.InteractionSession, err error) *LocalAuthUseCaseMock {
	e.results = &LocalAuthUseCaseMockGetInteractionSessionResults{ip1, err}
	return e.mock
}

// Times sets number of times LocalAuthUseCase.GetInteractionSession should be invoked
func (mmGetInteractionSession *mLocalAuthUseCaseMockGetInteractionSession) Times(n uint64) *mLocalAuthUseCaseMockGetInteractionSession {
	if n == 0 {
		mmGetInteractionSession.mock.t.Fatalf("Times of LocalAuthUseCaseMock.GetInteractionSession mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmGetInteractionSession.expectedInvocations, n)
	mmGetInteractionSession.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmGetInteractionSession
}

func (mmGetInteractionSession *mLocalAuthUseCaseMockGetInteractionSession) invocationsDone() bool {
	if len(mmGetInteractionSession.expectations) == 0 && mmGetInteractionSession.defaultExpectation == nil && mmGetInteractionSession.mock.funcGetInteractionSession == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmGetInteractionSession.mock.afterGetInteractionSessionCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmGetInteractionSession.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// GetInteractionSession implements mm_port.LocalAuthUseCase
func (mmGetInteractionSession *LocalAuthUseCaseMock) GetInteractionSession(ctx context.Context, tenantID uuid.UUID, interactionID string) (ip1 *model.InteractionSession, err error) {
	mm_atomic.AddUint64(&mmGetInteractionSession.beforeGetInteractionSessionCounter, 1)
	defer mm_atomic.AddUint64(&mmGetInteractionSession.afterGetInteractionSessionCounter, 1)

	mmGetInteractionSession.t.Helper()

	if mmGetInteractionSession.inspectFuncGetInteractionSession != nil {
		mmGetInteractionSession.inspectFuncGetInteractionSession(ctx, tenantID, interactionID)
	}

	mm_params := LocalAuthUseCaseMockGetInteractionSessionParams{ctx, tenantID, interactionID}

	// Record call args
	mmGetInteractionSession.GetInteractionSessionMock.mutex.Lock()
	mmGetInteractionSession.GetInteractionSessionMock.callArgs = append(mmGetInteractionSession.GetInteractionSessionMock.callArgs, &mm_params)
	mmGetInteractionSession.GetInteractionSessionMock.mutex.Unlock()

	for _, e := range mmGetInteractionSession.GetInteractionSessionMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.ip1, e.results.err
		}
	}

	if mmGetInteractionSession.GetInteractionSessionMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGetInteractionSession.GetInteractionSessionMock.defaultExpectation.Counter, 1)
		mm_want := mmGetInteractionSession.GetInteractionSessionMock.defaultExpectation.params
		mm_want_ptrs := mmGetInteractionSession.GetInteractionSessionMock.defaultExpectation.paramPtrs

		mm_got := LocalAuthUseCaseMockGetInteractionSessionParams{ctx, tenantID, interactionID}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmGetInteractionSession.t.Errorf("LocalAuthUseCaseMock.GetInteractionSession got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetInteractionSession.GetInteractionSessionMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.tenantID != nil && !minimock.Equal(*mm_want_ptrs.tenantID, mm_got.tenantID) {
				mmGetInteractionSession.t.Errorf("LocalAuthUseCaseMock.GetInteractionSession got unexpected parameter tenantID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetInteractionSession.GetInteractionSessionMock.defaultExpectation.expectationOrigins.originTenantID, *mm_want_ptrs.tenantID, mm_got.tenantID, minimock.Diff(*mm_want_ptrs.tenantID, mm_got.tenantID))
			}

			if mm_want_ptrs.interactionID != nil && !minimock.Equal(*mm_want_ptrs.interactionID, mm_got.interactionID) {
				mmGetInteractionSession.t.Errorf("LocalAuthUseCaseMock.GetInteractionSession got unexpected parameter interactionID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetInteractionSession.GetInteractionSessionMock.defaultExpectation.expectationOrigins.originInteractionID, *mm_want_ptrs.interactionID, mm_got.interactionID, minimock.Diff(*mm_want_ptrs.interactionID, mm_got.interactionID))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGetInteractionSession.t.Errorf("LocalAuthUseCaseMock.GetInteractionSession got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmGetInteractionSession.GetInteractionSessionMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGetInteractionSession.GetInteractionSessionMock.defaultExpectation.results
		if mm_results == nil {
			mmGetInteractionSession.t.Fatal("No results are set for the LocalAuthUseCaseMock.GetInteractionSession")
		}
		return (*mm_results).ip1, (*mm_results).err
	}
	if mmGetInteractionSession.funcGetInteractionSession != nil {
		return mmGetInteractionSession.funcGetInteractionSession(ctx, tenantID, interactionID)
	}
	mmGetInteractionSession.t.Fatalf("Unexpected call to LocalAuthUseCaseMock.GetInteractionSession. %v %v %v", ctx, tenantID, interactionID)
	return
}

// GetInteractionSessionAfterCounter returns a count of finished LocalAuthUseCaseMock.GetInteractionSession invocations
func (mmGetInteractionSession *LocalAuthUseCaseMock) GetInteractionSessionAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetInteractionSession.afterGetInteractionSessionCounter)
}

// GetInteractionSessionBeforeCounter returns a count of LocalAuthUseCaseMock.GetInteractionSession invocations
func (mmGetInteractionSession *LocalAuthUseCaseMock) GetInteractionSessionBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetInteractionSession.beforeGetInteractionSessionCounter)
}

// Calls returns a list of arguments used in each call to LocalAuthUseCaseMock.GetInteractionSession.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGetInteractionSession *mLocalAuthUseCaseMockGetInteractionSession) Calls() []*LocalAuthUseCaseMockGetInteractionSessionParams {
	mmGetInteractionSession.mutex.RLock()

	argCopy := make([]*LocalAuthUseCaseMockGetInteractionSessionParams, len(mmGetInteractionSession.callArgs))
	copy(argCopy, mmGetInteractionSession.callArgs)

	mmGetInteractionSession.mutex.RUnlock()

	return argCopy
}

// MinimockGetInteractionSessionDone returns true if the count of the GetInteractionSession invocations corresponds
// the number of defined expectations
func (m *LocalAuthUseCaseMock) MinimockGetInteractionSessionDone() bool {
	if m.GetInteractionSessionMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.GetInteractionSessionMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.GetInteractionSessionMock.invocationsDone()
}

// MinimockGetInteractionSessionInspect logs each unmet expectation
func (m *LocalAuthUseCaseMock) MinimockGetInteractionSessionInspect() {
	for _, e := range m.GetInteractionSessionMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to LocalAuthUseCaseMock.GetInteractionSession at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterGetInteractionSessionCounter := mm_atomic.LoadUint64(&m.afterGetInteractionSessionCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.GetInteractionSessionMock.defaultExpectation != nil && afterGetInteractionSessionCounter < 1 {
		if m.GetInteractionSessionMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to LocalAuthUseCaseMock.GetInteractionSession at\n%s", m.GetInteractionSessionMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to LocalAuthUseCaseMock.GetInteractionSession at\n%s with params: %#v", m.GetInteractionSessionMock.defaultExpectation.expectationOrigins.origin, *m.GetInteractionSessionMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetInteractionSession != nil && afterGetInteractionSessionCounter < 1 {
		m.t.Errorf("Expected call to LocalAuthUseCaseMock.GetInteractionSession at\n%s", m.funcGetInteractionSessionOrigin)
	}

	if !m.GetInteractionSessionMock.invocationsDone() && afterGetInteractionSessionCounter > 0 {
		m.t.Errorf("Expected %d calls to LocalAuthUseCaseMock.GetInteractionSession at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.GetInteractionSessionMock.expectedInvocations), m.GetInteractionSessionMock.expectedInvocationsOrigin, afterGetInteractionSessionCounter)
	}
}

type mLocalAuthUseCaseMockGetLoginContext struct {
	optional           bool
	mock               *LocalAuthUseCaseMock
	defaultExpectation *LocalAuthUseCaseMockGetLoginContextExpectation
	expectations       []*LocalAuthUseCaseMockGetLoginContextExpectation

	callArgs []*LocalAuthUseCaseMockGetLoginContextParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// LocalAuthUseCaseMockGetLoginContextExpectation specifies expectation struct of the LocalAuthUseCase.GetLoginContext
type LocalAuthUseCaseMockGetLoginContextExpectation struct {
	mock               *LocalAuthUseCaseMock
	params             *LocalAuthUseCaseMockGetLoginContextParams
	paramPtrs          *LocalAuthUseCaseMockGetLoginContextParamPtrs
	expectationOrigins LocalAuthUseCaseMockGetLoginContextExpectationOrigins
	results            *LocalAuthUseCaseMockGetLoginContextResults
	returnOrigin       string
	Counter            uint64
}

// LocalAuthUseCaseMockGetLoginContextParams contains parameters of the LocalAuthUseCase.GetLoginContext
type LocalAuthUseCaseMockGetLoginContextParams struct {
	ctx context.Context
	cmd mm_port.GetLoginContextCommand
}

// LocalAuthUseCaseMockGetLoginContextParamPtrs contains pointers to parameters of the LocalAuthUseCase.GetLoginContext
type LocalAuthUseCaseMockGetLoginContextParamPtrs struct {
	ctx *context.Context
	cmd *mm_port.GetLoginContextCommand
}

// LocalAuthUseCaseMockGetLoginContextResults contains results of the LocalAuthUseCase.GetLoginContext
type LocalAuthUseCaseMockGetLoginContextResults struct {
	lp1 *mm_port.LoginContextResponse
	err error
}

// LocalAuthUseCaseMockGetLoginContextOrigins contains origins of expectations of the LocalAuthUseCase.GetLoginContext
type LocalAuthUseCaseMockGetLoginContextExpectationOrigins struct {
	origin    string
	originCtx string
	originCmd string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmGetLoginContext *mLocalAuthUseCaseMockGetLoginContext) Optional() *mLocalAuthUseCaseMockGetLoginContext {
	mmGetLoginContext.optional = true
	return mmGetLoginContext
}

// Expect sets up expected params for LocalAuthUseCase.GetLoginContext
func (mmGetLoginContext *mLocalAuthUseCaseMockGetLoginContext) Expect(ctx context.Context, cmd mm_port.GetLoginContextCommand) *mLocalAuthUseCaseMockGetLoginContext {
	if mmGetLoginContext.mock.funcGetLoginContext != nil {
		mmGetLoginContext.mock.t.Fatalf("LocalAuthUseCaseMock.GetLoginContext mock is already set by Set")
	}

	if mmGetLoginContext.defaultExpectation == nil {
		mmGetLoginContext.defaultExpectation = &LocalAuthUseCaseMockGetLoginContextExpectation{}
	}

	if mmGetLoginContext.defaultExpectation.paramPtrs != nil {
		mmGetLoginContext.mock.t.Fatalf("LocalAuthUseCaseMock.GetLoginContext mock is already set by ExpectParams functions")
	}

	mmGetLoginContext.defaultExpectation.params = &LocalAuthUseCaseMockGetLoginContextParams{ctx, cmd}
	mmGetLoginContext.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmGetLoginContext.expectations {
		if minimock.Equal(e.params, mmGetLoginContext.defaultExpectation.params) {
			mmGetLoginContext.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGetLoginContext.defaultExpectation.params)
		}
	}

	return mmGetLoginContext
}

// ExpectCtxParam1 sets up expected param ctx for LocalAuthUseCase.GetLoginContext
func (mmGetLoginContext *mLocalAuthUseCaseMockGetLoginContext) ExpectCtxParam1(ctx context.Context) *mLocalAuthUseCaseMockGetLoginContext {
	if mmGetLoginContext.mock.funcGetLoginContext != nil {
		mmGetLoginContext.mock.t.Fatalf("LocalAuthUseCaseMock.GetLoginContext mock is already set by Set")
	}

	if mmGetLoginContext.defaultExpectation == nil {
		mmGetLoginContext.defaultExpectation = &LocalAuthUseCaseMockGetLoginContextExpectation{}
	}

	if mmGetLoginContext.defaultExpectation.params != nil {
		mmGetLoginContext.mock.t.Fatalf("LocalAuthUseCaseMock.GetLoginContext mock is already set by Expect")
	}

	if mmGetLoginContext.defaultExpectation.paramPtrs == nil {
		mmGetLoginContext.defaultExpectation.paramPtrs = &LocalAuthUseCaseMockGetLoginContextParamPtrs{}
	}
	mmGetLoginContext.defaultExpectation.paramPtrs.ctx = &ctx
	mmGetLoginContext.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmGetLoginContext
}

// ExpectCmdParam2 sets up expected param cmd for LocalAuthUseCase.GetLoginContext
func (mmGetLoginContext *mLocalAuthUseCaseMockGetLoginContext) ExpectCmdParam2(cmd mm_port.GetLoginContextCommand) *mLocalAuthUseCaseMockGetLoginContext {
	if mmGetLoginContext.mock.funcGetLoginContext != nil {
		mmGetLoginContext.mock.t.Fatalf("LocalAuthUseCaseMock.GetLoginContext mock is already set by Set")
	}

	if mmGetLoginContext.defaultExpectation == nil {
		mmGetLoginContext.defaultExpectation = &LocalAuthUseCaseMockGetLoginContextExpectation{}
	}

	if mmGetLoginContext.defaultExpectation.params != nil {
		mmGetLoginContext.mock.t.Fatalf("LocalAuthUseCaseMock.GetLoginContext mock is already set by Expect")
	}

	if mmGetLoginContext.defaultExpectation.paramPtrs == nil {
		mmGetLoginContext.defaultExpectation.paramPtrs = &LocalAuthUseCaseMockGetLoginContextParamPtrs{}
	}
	mmGetLoginContext.defaultExpectation.paramPtrs.cmd = &cmd
	mmGetLoginContext.defaultExpectation.expectationOrigins.originCmd = minimock.CallerInfo(1)

	return mmGetLoginContext
}

// Inspect accepts an inspector function that has same arguments as the LocalAuthUseCase.GetLoginContext
func (mmGetLoginContext *mLocalAuthUseCaseMockGetLoginContext) Inspect(f func(ctx context.Context, cmd mm_port.GetLoginContextCommand)) *mLocalAuthUseCaseMockGetLoginContext {
	if mmGetLoginContext.mock.inspectFuncGetLoginContext != nil {
		mmGetLoginContext.mock.t.Fatalf("Inspect function is already set for LocalAuthUseCaseMock.GetLoginContext")
	}

	mmGetLoginContext.mock.inspectFuncGetLoginContext = f

	return mmGetLoginContext
}

// Return sets up results that will be returned by LocalAuthUseCase.GetLoginContext
func (mmGetLoginContext *mLocalAuthUseCaseMockGetLoginContext) Return(lp1 *mm_port.LoginContextResponse, err error) *LocalAuthUseCaseMock {
	if mmGetLoginContext.mock.funcGetLoginContext != nil {
		mmGetLoginContext.mock.t.Fatalf("LocalAuthUseCaseMock.GetLoginContext mock is already set by Set")
	}

	if mmGetLoginContext.defaultExpectation == nil {
		mmGetLoginContext.defaultExpectation = &LocalAuthUseCaseMockGetLoginContextExpectation{mock: mmGetLoginContext.mock}
	}
	mmGetLoginContext.defaultExpectation.results = &LocalAuthUseCaseMockGetLoginContextResults{lp1, err}
	mmGetLoginContext.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmGetLoginContext.mock
}

// Set uses given function f to mock the LocalAuthUseCase.GetLoginContext method
func (mmGetLoginContext *mLocalAuthUseCaseMockGetLoginContext) Set(f func(ctx context.Context, cmd mm_port.GetLoginContextCommand) (lp1 *mm_port.LoginContextResponse, err error)) *LocalAuthUseCaseMock {
	if mmGetLoginContext.defaultExpectation != nil {
		mmGetLoginContext.mock.t.Fatalf("Default expectation is already set for the LocalAuthUseCase.GetLoginContext method")
	}

	if len(mmGetLoginContext.expectations) > 0 {
		mmGetLoginContext.mock.t.Fatalf("Some expectations are already set for the LocalAuthUseCase.GetLoginContext method")
	}

	mmGetLoginContext.mock.funcGetLoginContext = f
	mmGetLoginContext.mock.funcGetLoginContextOrigin = minimock.CallerInfo(1)
	return mmGetLoginContext.mock
}

// When sets expectation for the LocalAuthUseCase.GetLoginContext which will trigger the result defined by the following
// Then helper
func (mmGetLoginContext *mLocalAuthUseCaseMockGetLoginContext) When(ctx context.Context, cmd mm_port.GetLoginContextCommand) *LocalAuthUseCaseMockGetLoginContextExpectation {
	if mmGetLoginContext.mock.funcGetLoginContext != nil {
		mmGetLoginContext.mock.t.Fatalf("LocalAuthUseCaseMock.GetLoginContext mock is already set by Set")
	}

	expectation := &LocalAuthUseCaseMockGetLoginContextExpectation{
		mock:               mmGetLoginContext.mock,
		params:             &LocalAuthUseCaseMockGetLoginContextParams{ctx, cmd},
		expectationOrigins: LocalAuthUseCaseMockGetLoginContextExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmGetLoginContext.expectations = append(mmGetLoginContext.expectations, expectation)
	return expectation
}

// Then sets up LocalAuthUseCase.GetLoginContext return parameters for the expectation previously defined by the When method
func (e *LocalAuthUseCaseMockGetLoginContextExpectation) Then(lp1 *mm_port.LoginContextResponse, err error) *LocalAuthUseCaseMock {
	e.results = &LocalAuthUseCaseMockGetLoginContextResults{lp1, err}
	return e.mock
}

// Times sets number of times LocalAuthUseCase.GetLoginContext should be invoked
func (mmGetLoginContext *mLocalAuthUseCaseMockGetLoginContext) Times(n uint64) *mLocalAuthUseCaseMockGetLoginContext {
	if n == 0 {
		mmGetLoginContext.mock.t.Fatalf("Times of LocalAuthUseCaseMock.GetLoginContext mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmGetLoginContext.expectedInvocations, n)
	mmGetLoginContext.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmGetLoginContext
}

func (mmGetLoginContext *mLocalAuthUseCaseMockGetLoginContext) invocationsDone() bool {
	if len(mmGetLoginContext.expectations) == 0 && mmGetLoginContext.defaultExpectation == nil && mmGetLoginContext.mock.funcGetLoginContext == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmGetLoginContext.mock.afterGetLoginContextCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmGetLoginContext.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// GetLoginContext implements mm_port.LocalAuthUseCase
func (mmGetLoginContext *LocalAuthUseCaseMock) GetLoginContext(ctx context.Context, cmd mm_port.GetLoginContextCommand) (lp1 *mm_port.LoginContextResponse, err error) {
	mm_atomic.AddUint64(&mmGetLoginContext.beforeGetLoginContextCounter, 1)
	defer mm_atomic.AddUint64(&mmGetLoginContext.afterGetLoginContextCounter, 1)

	mmGetLoginContext.t.Helper()

	if mmGetLoginContext.inspectFuncGetLoginContext != nil {
		mmGetLoginContext.inspectFuncGetLoginContext(ctx, cmd)
	}

	mm_params := LocalAuthUseCaseMockGetLoginContextParams{ctx, cmd}

	// Record call args
	mmGetLoginContext.GetLoginContextMock.mutex.Lock()
	mmGetLoginContext.GetLoginContextMock.callArgs = append(mmGetLoginContext.GetLoginContextMock.callArgs, &mm_params)
	mmGetLoginContext.GetLoginContextMock.mutex.Unlock()

	for _, e := range mmGetLoginContext.GetLoginContextMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.lp1, e.results.err
		}
	}

	if mmGetLoginContext.GetLoginContextMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGetLoginContext.GetLoginContextMock.defaultExpectation.Counter, 1)
		mm_want := mmGetLoginContext.GetLoginContextMock.defaultExpectation.params
		mm_want_ptrs := mmGetLoginContext.GetLoginContextMock.defaultExpectation.paramPtrs

		mm_got := LocalAuthUseCaseMockGetLoginContextParams{ctx, cmd}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmGetLoginContext.t.Errorf("LocalAuthUseCaseMock.GetLoginContext got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetLoginContext.GetLoginContextMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.cmd != nil && !minimock.Equal(*mm_want_ptrs.cmd, mm_got.cmd) {
				mmGetLoginContext.t.Errorf("LocalAuthUseCaseMock.GetLoginContext got unexpected parameter cmd, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetLoginContext.GetLoginContextMock.defaultExpectation.expectationOrigins.originCmd, *mm_want_ptrs.cmd, mm_got.cmd, minimock.Diff(*mm_want_ptrs.cmd, mm_got.cmd))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGetLoginContext.t.Errorf("LocalAuthUseCaseMock.GetLoginContext got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmGetLoginContext.GetLoginContextMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGetLoginContext.GetLoginContextMock.defaultExpectation.results
		if mm_results == nil {
			mmGetLoginContext.t.Fatal("No results are set for the LocalAuthUseCaseMock.GetLoginContext")
		}
		return (*mm_results).lp1, (*mm_results).err
	}
	if mmGetLoginContext.funcGetLoginContext != nil {
		return mmGetLoginContext.funcGetLoginContext(ctx, cmd)
	}
	mmGetLoginContext.t.Fatalf("Unexpected call to LocalAuthUseCaseMock.GetLoginContext. %v %v", ctx, cmd)
	return
}

// GetLoginContextAfterCounter returns a count of finished LocalAuthUseCaseMock.GetLoginContext invocations
func (mmGetLoginContext *LocalAuthUseCaseMock) GetLoginContextAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetLoginContext.afterGetLoginContextCounter)
}

// GetLoginContextBeforeCounter returns a count of LocalAuthUseCaseMock.GetLoginContext invocations
func (mmGetLoginContext *LocalAuthUseCaseMock) GetLoginContextBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetLoginContext.beforeGetLoginContextCounter)
}

// Calls returns a list of arguments used in each call to LocalAuthUseCaseMock.GetLoginContext.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGetLoginContext *mLocalAuthUseCaseMockGetLoginContext) Calls() []*LocalAuthUseCaseMockGetLoginContextParams {
	mmGetLoginContext.mutex.RLock()

	argCopy := make([]*LocalAuthUseCaseMockGetLoginContextParams, len(mmGetLoginContext.callArgs))
	copy(argCopy, mmGetLoginContext.callArgs)

	mmGetLoginContext.mutex.RUnlock()

	return argCopy
}

// MinimockGetLoginContextDone returns true if the count of the GetLoginContext invocations corresponds
// the number of defined expectations
func (m *LocalAuthUseCaseMock) MinimockGetLoginContextDone() bool {
	if m.GetLoginContextMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.GetLoginContextMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.GetLoginContextMock.invocationsDone()
}

// MinimockGetLoginContextInspect logs each unmet expectation
func (m *LocalAuthUseCaseMock) MinimockGetLoginContextInspect() {
	for _, e := range m.GetLoginContextMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to LocalAuthUseCaseMock.GetLoginContext at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterGetLoginContextCounter := mm_atomic.LoadUint64(&m.afterGetLoginContextCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.GetLoginContextMock.defaultExpectation != nil && afterGetLoginContextCounter < 1 {
		if m.GetLoginContextMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to LocalAuthUseCaseMock.GetLoginContext at\n%s", m.GetLoginContextMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to LocalAuthUseCaseMock.GetLoginContext at\n%s with params: %#v", m.GetLoginContextMock.defaultExpectation.expectationOrigins.origin, *m.GetLoginContextMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetLoginContext != nil && afterGetLoginContextCounter < 1 {
		m.t.Errorf("Expected call to LocalAuthUseCaseMock.GetLoginContext at\n%s", m.funcGetLoginContextOrigin)
	}

	if !m.GetLoginContextMock.invocationsDone() && afterGetLoginContextCounter > 0 {
		m.t.Errorf("Expected %d calls to LocalAuthUseCaseMock.GetLoginContext at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.GetLoginContextMock.expectedInvocations), m.GetLoginContextMock.expectedInvocationsOrigin, afterGetLoginContextCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *LocalAuthUseCaseMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockAuthenticateLocalCredentialsInspect()

			m.MinimockGetInteractionSessionInspect()

			m.MinimockGetLoginContextInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *LocalAuthUseCaseMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *LocalAuthUseCaseMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockAuthenticateLocalCredentialsDone() &&
		m.MinimockGetInteractionSessionDone() &&
		m.MinimockGetLoginContextDone()
}
